libsemigroups::Action: 
- Member types:
  - ["This page contains information about the member types of the
     :cpp:any:`Action` class."]
  - element_type
  - point_type
  - const_reference_point_type
  - const_pointer_point_type
  - index_type
  - scc_index_type
  - const_iterator
  - const_iterator_scc
  - const_iterator_scc_roots
  - const_iterator_sccs
  - action_type
- Constructors:
  - ["This page contains information about the constructors for the
     :cpp:any:`Action` class."]
  - Action()
  - Action(Action const&) = default
  - Action(Action&&) = default
  - operator=(Action const&) = default
  - operator=(Action&&) = default
- Initialization:
  - ["This page contains information about initialising the
     :cpp:any:`Action` class."]
  - reserve(size_t)
  - add_seed(const_reference_point_type)
  - add_generator(element_type)
- Position, size, empty...: 
  - ["This page contains information about accessing the values in an instance
     of the :cpp:any:`Action` class."]
  - position(const_reference_point_type) const
  - empty() const noexcept
  - operator[](size_t) const noexcept
  - at(size_t) const
  - size()
  - current_size() const noexcept
  - cbegin() const noexcept
  - cend() const noexcept
- Strongly connected components:
  - ["This page contains information about the functionality for strongly
     connected components in the :cpp:any:`Action` class."]
  - cache_scc_multipliers() const noexcept
  - cache_scc_multipliers(bool) noexcept
  - digraph()
  - multiplier_from_scc_root(index_type)
  - multiplier_to_scc_root(index_type)
  - root_of_scc(const_reference_point_type)
  - root_of_scc(index_type)
- Member functions inherited from Runner:
  - ["This page contains information about reporting for the
     :cpp:any:`Action` class. These functions described on this
     page are implemented in :cpp:any:`libsemigroups::Runner`."]
  - dead() const noexcept
  - finished() const
  - started() const
  - stopped() const
  - timed_out() const
  - running() const noexcept
  - stopped_by_predicate() const
  - kill() noexcept
  - run()
  - run_for(std::chrono::nanoseconds)
  - run_for(TIntType)
  - run_until(T&&)
  - run_until(bool(*)())
  - report_every(TIntType)
  - report_every(std::chrono::nanoseconds)
  - report_every() const noexcept
  - report() const
  - report_why_we_stopped() const
  - running_for() const noexcept
  - running_until() const noexcept
