github_checks:
  annotations: false

coverage:
  precision: 2
  round: down
  range: "90...100"

  status: # GitHub status checks to add to a PR
    project:
      default:
        informational: true # Don't fail the check if overall coverage decreases
    patch: # Check only the PR's diff
      default:
        target: 100
        threshold: 0
        informational: true # Do fail the check if the diff is not 100% covered
    changes: # Information about changes in coverage outside the diff
      default:
        informational: true # Don't fail the check

# Comment to post on PRs
comment: true

ignore:
 - "extern"
 - "tests"
