exclude: |
  (?x)^(
    third_party/.*|
    (tests|benchmarks)/catch_.*\.(c|h|t)pp|
    m4/.*|
    docs/doxygen-awesome-css/.*
  )$
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        files: ^(include/libsemigroups|src|tests|benchmarks)/.*\.(c|h|t)pp$
  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.2
    hooks:
      - id: cpplint
        stages: ["pre-push"]
        files: |
          (?x)^(
            include/libsemigroups/.*\.(h|t)pp|
            src/.*\.cpp|
            tests/.*\.cpp|
            benchmarks/.*\.cpp
          )$
        args: ["--repository=include", "--extensions=cpp,hpp,tpp"]
      - id: cpplint
        name: cpplint-extras
        alias: cpplint-extras
        stages: ["pre-push"]
        files: |
          (?x)^(
            tests/.*\.hpp|
            benchmarks/.*\.hpp
          )$
        args: ["--repository=..", "--extensions=hpp"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        stages: ["pre-push"]
