name: libsemigroups_dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.13
  - autoconf
  - automake
  - bs4
  - ccache
  - clang-format-15
  - codespell
  - cpplint
  - doxygen
  - gitpython
  - graphviz
  - libtool
  - lxml
  - matplotlib
  - numpy
  - pandas
  - pip
  - rich
  - seaborn
  - pip:
      - accepts
