var NAVTREEINDEX0 = 
{'_HEADING_': [31],
 'citelist.html': [30],
 'classlibsemigroups_1_1_action.html': [18, 1],
 'classlibsemigroups_1_1_bipartition.html': [5, 0, 0],
 'classlibsemigroups_1_1_blocks.html': [5, 0, 1],
 'classlibsemigroups_1_1_dynamic_matrix_3_01_plus_op_00_01_prod_op_00_01_zero_op_00_01_one_op_00_01_scalar_01_4.html#DynamicMatrixStaticArith': [5,
                                                                                                                                                 1,
                                                                                                                                                 1,
                                                                                                                                                 0],
 'classlibsemigroups_1_1_dynamic_matrix_3_01_semiring_00_01_scalar_01_4.html#DynamicMatrixDynamicArith': [5,
                                                                                                          1,
                                                                                                          1,
                                                                                                          1],
 'classlibsemigroups_1_1_dynamic_row_view_3_01_plus_op_00_01_prod_op_00_01_zero_op_00_01_one_op_00_01_scalar_01_4.html#DynamicRowViewStaticArith': [5,
                                                                                                                                                    1,
                                                                                                                                                    2,
                                                                                                                                                    0],
 'classlibsemigroups_1_1_dynamic_row_view_3_01_semiring_00_01_scalar_01_4.html#DynamicRowViewDynamicArith': [5,
                                                                                                             1,
                                                                                                             2,
                                                                                                             1],
 'classlibsemigroups_1_1_forest.html': [15, 0],
 'classlibsemigroups_1_1_froidure_pin.html': [21, 0],
 'classlibsemigroups_1_1_froidure_pin_base.html': [21, 1],
 'classlibsemigroups_1_1_inverse_presentation.html': [8, 1],
 'classlibsemigroups_1_1_joiner.html': [15, 3],
 'classlibsemigroups_1_1_meeter.html': [15, 4],
 'classlibsemigroups_1_1_minimal_rep_orc.html': [26, 0, 0],
 'classlibsemigroups_1_1_p_b_r.html': [5, 2, 0],
 'classlibsemigroups_1_1_presentation.html': [8, 0],
 'classlibsemigroups_1_1_rank_state.html': [4, 1, 5],
 'classlibsemigroups_1_1_rep_orc.html': [26, 0, 1],
 'classlibsemigroups_1_1_reporter.html': [6, 3],
 'classlibsemigroups_1_1_runner.html': [6, 4],
 'classlibsemigroups_1_1_sims1.html': [26, 0, 2],
 'classlibsemigroups_1_1_sims2.html': [26, 0, 3],
 'classlibsemigroups_1_1_sims_refiner_faithful.html': [26, 0, 7],
 'classlibsemigroups_1_1_sims_refiner_ideals.html': [26, 0, 4],
 'classlibsemigroups_1_1_sims_settings.html': [26, 0, 5],
 'classlibsemigroups_1_1_sims_stats.html': [26, 0, 6],
 'classlibsemigroups_1_1_static_matrix.html': [5, 1, 1, 2],
 'classlibsemigroups_1_1_static_row_view.html': [5, 1, 2, 2],
 'classlibsemigroups_1_1_stephen.html': [27, 0],
 'classlibsemigroups_1_1_string_range.html': [16, 1],
 'classlibsemigroups_1_1_to_string.html': [16, 3],
 'classlibsemigroups_1_1_to_word.html': [16, 2],
 'classlibsemigroups_1_1_word_graph.html': [15, 6],
 'classlibsemigroups_1_1_word_range.html': [16, 0],
 'group__action__group.html': [18],
 'group__action__group.html#ga1288ede08d1b9494336b874ad4da177e': [18, 2],
 'group__action__group.html#gafc015eff6557e84151d2e53b94375445': [18, 0],
 'group__adapters__bmat8__group.html': [4, 3],
 'group__adapters__bmat__group.html': [4, 2],
 'group__adapters__group.html': [4],
 'group__adapters__hpcombi__group.html': [4, 5],
 'group__adapters__matrix__group.html': [4, 4],
 'group__adapters__pbr__group.html': [4, 6],
 'group__aho__corasick__group.html': [11],
 'group__bipart__group.html': [5, 0],
 'group__bmat__index__group.html': [5, 1, 0, 0],
 'group__cong__common__helpers__add__pair__group.html': [19, 0],
 'group__cong__common__helpers__contains__group.html': [19, 1],
 'group__cong__common__helpers__group.html': [19],
 'group__cong__common__helpers__partition__group.html': [19, 3],
 'group__cong__common__helpers__reduce__group.html': [19, 2],
 'group__congruence__class__accessors__group.html': [20, 0, 4],
 'group__congruence__class__group.html': [20, 0],
 'group__congruence__class__init__group.html': [20, 0, 1],
 'group__congruence__class__intf__group.html': [20, 0, 3],
 'group__congruence__class__mem__types__group.html': [20, 0, 0],
 'group__congruence__class__settings__group.html': [20, 0, 2],
 'group__congruence__group.html': [20],
 'group__congruence__helpers__group.html': [20, 1],
 'group__constants__group.html': [6, 0],
 'group__dot__group.html': [14],
 'group__elements__group.html': [5],
 'group__exception__group.html': [6, 2],
 'group__freeband__group.html': [24],
 'group__froidure__pin__group.html': [21],
 'group__gabow__group.html': [15, 2],
 'group__intmat__group.html': [5, 1, 0, 1],
 'group__kambites__class__accessors__group.html': [22, 0, 3],
 'group__kambites__class__group.html': [22, 0],
 'group__kambites__class__init__group.html': [22, 0, 1],
 'group__kambites__class__intf__group.html': [22, 0, 2],
 'group__kambites__class__mem__types__group.html': [22, 0, 0],
 'group__kambites__group.html': [22],
 'group__kambites__helpers__group.html': [22, 1],
 'group__knuth__bendix__class__accessors__group.html': [23, 0, 4],
 'group__knuth__bendix__class__group.html': [23, 0],
 'group__knuth__bendix__class__init__group.html': [23, 0, 1],
 'group__knuth__bendix__class__intf__group.html': [23, 0, 3],
 'group__knuth__bendix__class__mem__types__group.html': [23, 0, 0],
 'group__knuth__bendix__class__settings__group.html': [23, 0, 2],
 'group__knuth__bendix__group.html': [23],
 'group__knuth__bendix__helpers__group.html': [23, 1],
 'group__make__bipart__group.html': [5, 0, 4],
 'group__make__blocks__group.html': [5, 0, 5],
 'group__make__forest__group.html': [15, 1],
 'group__make__froidure__pin__group.html': [21, 5],
 'group__make__group.html': [12],
 'group__make__matrix__group.html': [5, 1, 3],
 'group__make__pbr__group.html': [5, 2, 2],
 'group__make__word__graph__group.html': [15, 8],
 'group__matrix__group.html': [5, 1],
 'group__maxplusmat__group.html': [5, 1, 0, 2],
 'group__maxplustruncmat__group.html': [5, 1, 0, 4],
 'group__minplusmat__group.html': [5, 1, 0, 3],
 'group__minplustruncmat__group.html': [5, 1, 0, 5],
 'group__misc__group.html': [6],
 'group__ntpmat__group.html': [5, 1, 0, 6],
 'group__obvinf__group.html': [6, 1],
 'group__orders__group.html': [7],
 'group__paths__group.html': [15, 5],
 'group__pbr__group.html': [5, 2],
 'group__presentations__group.html': [8],
 'group__projmaxplus__group.html': [5, 1, 0, 7],
 'group__ranges__group.html': [9],
 'group__schreier__sims__group.html': [25],
 'group__sims__group.html': [26],
 'group__sims__group.html#nested-classes': [26, 0],
 'group__stephen__group.html': [27],
 'group__to__cong__group.html': [20, 2],
 'group__to__froidure__pin__group.html': [21, 4],
 'group__to__group.html': [13],
 'group__to__inverse__presentation__group.html': [8, 5],
 'group__to__knuth__bendix__group.html': [23, 2],
 'group__to__presentation__group.html': [8, 4],
 'group__to__todd__coxeter__group.html': [28, 2],
 'group__todd__coxeter__class__accessors__group.html': [28, 0, 4],
 'group__todd__coxeter__class__group.html': [28, 0],
 'group__todd__coxeter__class__index__word__group.html': [28, 0, 7],
 'group__todd__coxeter__class__init__group.html': [28, 0, 1],
 'group__todd__coxeter__class__intf__group.html': [28, 0, 3],
 'group__todd__coxeter__class__mem__types__group.html': [28, 0, 0],
 'group__todd__coxeter__class__mod__group.html': [28, 0, 5],
 'group__todd__coxeter__class__settings__group.html': [28, 0, 2],
 'group__todd__coxeter__class__word__index__group.html': [28, 0, 6],
 'group__todd__coxeter__group.html': [28],
 'group__todd__coxeter__helpers__group.html': [28, 1],
 'group__transf__group.html': [5, 3],
 'group__types__group.html': [6, 5],
 'group__ukkonen__group.html': [10],
 'group__word__graph__group.html': [15],
 'group__words__group.html': [16],
 'index.html#autotoc_md10': [0, 0],
 'index.html#autotoc_md11': [0, 1],
 'index.html#autotoc_md12': [0, 2],
 'index.html#autotoc_md13': [0, 3],
 'index.html#autotoc_md14': [0, 4],
 'index.html#autotoc_md15': [0, 5],
 'index.html#autotoc_md16': [0, 6],
 'index.html#autotoc_md9': [0],
 'md_install.html': [2],
 'namespacelibsemigroups_1_1bipartition.html': [5, 0, 2],
 'namespacelibsemigroups_1_1blocks.html': [5, 0, 3],
 'namespacelibsemigroups_1_1froidure__pin.html': [21, 3],
 'namespacelibsemigroups_1_1literals.html': [16, 5],
 'namespacelibsemigroups_1_1pbr.html': [5, 2, 1],
 'namespacelibsemigroups_1_1presentation.html': [8, 2],
 'namespacelibsemigroups_1_1presentation_1_1examples.html': [8, 3],
 'namespacelibsemigroups_1_1sims.html': [26, 1],
 'namespacelibsemigroups_1_1stephen.html': [27, 1],
 'namespacelibsemigroups_1_1word__graph.html': [15, 7],
 'namespacelibsemigroups_1_1words.html': [16, 4],
 'structlibsemigroups_1_1_complexity.html': [4, 0, 0],
 'structlibsemigroups_1_1_degree.html': [4, 0, 1],
 'structlibsemigroups_1_1_equal_to.html': [4, 1, 0],
 'structlibsemigroups_1_1_froidure_pin_traits.html': [21, 2],
 'structlibsemigroups_1_1_hash.html': [4, 1, 1],
 'structlibsemigroups_1_1_image_left_action.html': [4, 0, 2],
 'structlibsemigroups_1_1_image_right_action.html': [4, 0, 3],
 'structlibsemigroups_1_1_increase_degree.html': [4, 0, 4],
 'structlibsemigroups_1_1_inverse.html': [4, 0, 5],
 'structlibsemigroups_1_1_lambda.html': [4, 0, 6],
 'structlibsemigroups_1_1_lambda_value.html': [4, 0, 7],
 'structlibsemigroups_1_1_less.html': [4, 1, 2],
 'structlibsemigroups_1_1_on_sets.html': [4, 1, 4],
 'structlibsemigroups_1_1_on_tuples.html': [4, 1, 3],
 'structlibsemigroups_1_1_one.html': [4, 0, 8],
 'structlibsemigroups_1_1_product.html': [4, 0, 9],
 'structlibsemigroups_1_1_rho.html': [4, 0, 10],
 'structlibsemigroups_1_1_rho_value.html': [4, 0, 11],
 'structlibsemigroups_1_1_swap.html': [4, 1, 6],
 'structlibsemigroups_1_1_todd_coxeter_1_1options.html': [28, 0, 0, 0]};

