var NAVTREEINDEX0 = 
{'_HEADING_': [26],
 'citelist.html': [3],
 'classlibsemigroups_1_1Action.html': [27, 0],
 'classlibsemigroups_1_1AhoCorasick.html': [21, 0],
 'classlibsemigroups_1_1BMat8.html': [12, 1, 0, 0, 0, 0],
 'classlibsemigroups_1_1Bipartition.html': [12, 0, 0],
 'classlibsemigroups_1_1Blocks.html': [12, 0, 1],
 'classlibsemigroups_1_1Dot.html': [23, 0],
 'classlibsemigroups_1_1DynamicMatrix_3_01PlusOp_00_01ProdOp_00_01ZeroOp_00_01OneOp_00_01Scalar_01_4.html': [12,
                                                                                                             1,
                                                                                                             1,
                                                                                                             0],
 'classlibsemigroups_1_1DynamicMatrix_3_01Semiring_00_01Scalar_01_4.html': [12,
                                                                            1,
                                                                            1,
                                                                            1],
 'classlibsemigroups_1_1DynamicPTransf.html': [12, 3, 0],
 'classlibsemigroups_1_1DynamicRowView_3_01PlusOp_00_01ProdOp_00_01ZeroOp_00_01OneOp_00_01Scalar_01_4.html#DynamicRowViewStaticArith': [12,
                                                                                                                                        1,
                                                                                                                                        2,
                                                                                                                                        0],
 'classlibsemigroups_1_1DynamicRowView_3_01Semiring_00_01Scalar_01_4.html#DynamicRowViewDynamicArith': [12,
                                                                                                        1,
                                                                                                        2,
                                                                                                        1],
 'classlibsemigroups_1_1Forest.html': [24, 0],
 'classlibsemigroups_1_1FroidurePin.html': [31, 0],
 'classlibsemigroups_1_1FroidurePinBase.html': [31, 1],
 'classlibsemigroups_1_1Gabow.html': [24, 1],
 'classlibsemigroups_1_1InversePresentation.html': [16, 1],
 'classlibsemigroups_1_1IsObviouslyInfinite.html': [16, 6, 0],
 'classlibsemigroups_1_1Joiner.html': [24, 2],
 'classlibsemigroups_1_1Konieczny.html': [34, 0],
 'classlibsemigroups_1_1Konieczny_1_1DClass.html': [34, 2],
 'classlibsemigroups_1_1MaxPlusTruncSemiring.html': [12, 1, 0, 4, 1],
 'classlibsemigroups_1_1Meeter.html': [24, 3],
 'classlibsemigroups_1_1MinPlusTruncSemiring.html': [12, 1, 0, 5, 1],
 'classlibsemigroups_1_1MinimalRepOrc.html': [35, 0, 0],
 'classlibsemigroups_1_1NTPSemiring.html': [12, 1, 0, 6, 2],
 'classlibsemigroups_1_1PBR.html': [12, 2, 0],
 'classlibsemigroups_1_1PPerm.html': [12, 3, 2],
 'classlibsemigroups_1_1PTransfBase.html': [12, 3, 3],
 'classlibsemigroups_1_1Paths.html': [24, 4],
 'classlibsemigroups_1_1Perm.html': [12, 3, 1],
 'classlibsemigroups_1_1Presentation.html': [16, 0],
 'classlibsemigroups_1_1RankState.html': [10, 1, 5],
 'classlibsemigroups_1_1RankState_3_01Mat_01_4.html': [10, 2, 6],
 'classlibsemigroups_1_1RepOrc.html': [35, 0, 1],
 'classlibsemigroups_1_1Reporter.html': [30, 0],
 'classlibsemigroups_1_1Runner.html': [30, 2],
 'classlibsemigroups_1_1SchreierSims.html': [37, 0],
 'classlibsemigroups_1_1Sims1.html': [35, 0, 2],
 'classlibsemigroups_1_1Sims2.html': [35, 0, 3],
 'classlibsemigroups_1_1SimsRefinerFaithful.html': [35, 0, 4],
 'classlibsemigroups_1_1SimsRefinerIdeals.html': [35, 0, 5],
 'classlibsemigroups_1_1SimsSettings.html': [35, 0, 6],
 'classlibsemigroups_1_1SimsStats.html': [35, 0, 7],
 'classlibsemigroups_1_1StaticMatrix.html': [12, 1, 1, 2],
 'classlibsemigroups_1_1StaticPTransf.html': [12, 3, 4],
 'classlibsemigroups_1_1StaticRowView.html': [12, 1, 2, 2],
 'classlibsemigroups_1_1Stephen.html': [38, 0],
 'classlibsemigroups_1_1StringRange.html': [25, 0],
 'classlibsemigroups_1_1ToString.html': [25, 2],
 'classlibsemigroups_1_1ToWord.html': [25, 3],
 'classlibsemigroups_1_1Transf.html': [12, 3, 5],
 'classlibsemigroups_1_1Ukkonen.html': [18, 0],
 'classlibsemigroups_1_1WordGraph.html': [24, 5],
 'classlibsemigroups_1_1WordGraphView.html': [24, 6],
 'classlibsemigroups_1_1WordRange.html': [25, 1],
 'group__action__group.html': [27],
 'group__adapters__bmat8__group.html': [10, 3],
 'group__adapters__bmat__group.html': [10, 2],
 'group__adapters__group.html': [10],
 'group__adapters__hpcombi__group.html': [14, 0],
 'group__adapters__matrix__group.html': [10, 4],
 'group__adapters__pbr__group.html': [10, 6],
 'group__aho__corasick__group.html': [21],
 'group__bipart__group.html': [12, 0],
 'group__bmat8__group.html': [12, 1, 0, 0, 0],
 'group__bmat__group.html': [12, 1, 0, 0, 1],
 'group__bmat__index__group.html': [12, 1, 0, 0],
 'group__cong__common__helpers__add__pair__group.html': [28, 0],
 'group__cong__common__helpers__contains__group.html': [28, 1],
 'group__cong__common__helpers__group.html': [28],
 'group__cong__common__helpers__partition__group.html': [28, 3],
 'group__cong__common__helpers__reduce__group.html': [28, 2],
 'group__congruence__class__accessors__group.html': [29, 0, 4],
 'group__congruence__class__group.html': [29, 0],
 'group__congruence__class__init__group.html': [29, 0, 1],
 'group__congruence__class__intf__group.html': [29, 0, 3],
 'group__congruence__class__mem__types__group.html': [29, 0, 0],
 'group__congruence__class__settings__group.html': [29, 0, 2],
 'group__congruence__group.html': [29],
 'group__congruence__helpers__group.html': [29, 1],
 'group__constants__group.html': [11],
 'group__core__classes__group.html': [30],
 'group__dot__group.html': [23],
 'group__elements__group.html': [12],
 'group__exception__group.html': [13],
 'group__freeband__group.html': [36],
 'group__froidure__pin__group.html': [31],
 'group__hpcombi__group.html': [14],
 'group__intmat__group.html': [12, 1, 0, 1],
 'group__kambites__class__accessors__group.html': [32, 0, 3],
 'group__kambites__class__group.html': [32, 0],
 'group__kambites__class__init__group.html': [32, 0, 1],
 'group__kambites__class__intf__group.html': [32, 0, 2],
 'group__kambites__class__mem__types__group.html': [32, 0, 0],
 'group__kambites__group.html': [32],
 'group__kambites__helpers__group.html': [32, 1],
 'group__knuth__bendix__class__accessors__group.html': [33, 0, 4],
 'group__knuth__bendix__class__group.html': [33, 0],
 'group__knuth__bendix__class__init__group.html': [33, 0, 1],
 'group__knuth__bendix__class__intf__group.html': [33, 0, 3],
 'group__knuth__bendix__class__mem__types__group.html': [33, 0, 0],
 'group__knuth__bendix__class__settings__group.html': [33, 0, 2],
 'group__knuth__bendix__group.html': [33],
 'group__knuth__bendix__helpers__group.html': [33, 1],
 'group__konieczny__group.html': [34],
 'group__make__bipart__group.html': [12, 0, 4],
 'group__make__blocks__group.html': [12, 0, 5],
 'group__make__forest__group.html': [24, 10],
 'group__make__froidure__pin__group.html': [31, 5],
 'group__make__group.html': [19],
 'group__make__hpcombi__group.html': [14, 1],
 'group__make__konieczny__group.html': [34, 4],
 'group__make__matrix__group.html': [12, 1, 3],
 'group__make__pbr__group.html': [12, 2, 2],
 'group__make__perm__group.html': [12, 3, 8],
 'group__make__pperm__group.html': [12, 3, 7],
 'group__make__transf__group.html': [12, 3, 6],
 'group__make__word__graph__group.html': [24, 11],
 'group__matrix__group.html': [12, 1],
 'group__maxplusmat__group.html': [12, 1, 0, 2],
 'group__maxplustruncmat__group.html': [12, 1, 0, 4],
 'group__minplusmat__group.html': [12, 1, 0, 3],
 'group__minplustruncmat__group.html': [12, 1, 0, 5],
 'group__ntpmat__group.html': [12, 1, 0, 6],
 'group__obvinf__group.html': [16, 6],
 'group__orders__group.html': [15],
 'group__pbr__group.html': [12, 2],
 'group__presentations__group.html': [16],
 'group__projmaxplus__group.html': [12, 1, 0, 7],
 'group__ranges__group.html': [17],
 'group__schreier__sims__group.html': [37],
 'group__sims__group.html': [35],
 'group__sims__group.html#nested-classes': [35, 0],
 'group__stephen__group.html': [38],
 'group__to__cong__group.html': [29, 2],
 'group__to__froidure__pin__group.html': [31, 4],
 'group__to__group.html': [20],
 'group__to__inverse__presentation__group.html': [16, 5],
 'group__to__knuth__bendix__group.html': [33, 2],
 'group__to__presentation__group.html': [16, 4],
 'group__to__todd__coxeter__group.html': [39, 2],
 'group__to__word__graph__group.html': [24, 12],
 'group__todd__coxeter__class__accessors__group.html': [39, 0, 5],
 'group__todd__coxeter__class__group.html': [39, 0],
 'group__todd__coxeter__class__index__word__group.html': [39, 0, 8],
 'group__todd__coxeter__class__init__group.html': [39, 0, 2],
 'group__todd__coxeter__class__intf__group.html': [39, 0, 4],
 'group__todd__coxeter__class__mem__types__group.html': [39, 0, 1],
 'group__todd__coxeter__class__mod__group.html': [39, 0, 6],
 'group__todd__coxeter__class__settings__group.html': [39, 0, 3],
 'group__todd__coxeter__class__word__index__group.html': [39, 0, 7],
 'group__todd__coxeter__group.html': [39],
 'group__todd__coxeter__helpers__group.html': [39, 1],
 'group__transf__group.html': [12, 3],
 'group__types__group.html': [22],
 'group__ukkonen__group.html': [18],
 'group__word__graph__group.html': [24],
 'group__words__group.html': [25],
 'index.html#acknowledgements': [0, 6],
 'index.html#dependencies': [0, 5],
 'index.html#design-principles': [0, 1],
 'index.html#how-to-use-libsemigroups': [0, 2],
 'index.html#installation': [0, 3],
 'index.html#issues': [0, 4],
 'index.html#libsemigroups': [0],
 'index.html#what-is-libsemigroups': [0, 0],
 'md_authors.html': [2],
 'md_changelog-v1.html': [6],
 'md_changelog-v2.html': [5],
 'md_changelog-v3.html': [4],
 'md_deprecate.html': [7],
 'md_install.html': [8],
 'md_todd-coxeter-report.html': [39, 0, 0],
 'namespacelibsemigroups_1_1aho__corasick.html': [21, 1],
 'namespacelibsemigroups_1_1bipartition.html': [12, 0, 2],
 'namespacelibsemigroups_1_1blocks.html': [12, 0, 3],
 'namespacelibsemigroups_1_1bmat8.html': [12, 1, 0, 0, 0, 1],
 'namespacelibsemigroups_1_1forest.html': [24, 7],
 'namespacelibsemigroups_1_1froidure__pin.html': [31, 3],
 'namespacelibsemigroups_1_1konieczny.html': [34, 3],
 'namespacelibsemigroups_1_1literals.html': [25, 5],
 'namespacelibsemigroups_1_1paths.html': [24, 8],
 'namespacelibsemigroups_1_1pbr.html': [12, 2, 1],
 'namespacelibsemigroups_1_1presentation.html': [16, 2],
 'namespacelibsemigroups_1_1presentation_1_1examples.html': [16, 3],
 'namespacelibsemigroups_1_1schreier__sims.html': [37, 2],
 'namespacelibsemigroups_1_1sims.html': [35, 1],
 'namespacelibsemigroups_1_1stephen.html': [38, 1],
 'namespacelibsemigroups_1_1ukkonen.html': [18, 1],
 'namespacelibsemigroups_1_1word__graph.html': [24, 9],
 'namespacelibsemigroups_1_1words.html': [25, 4],
 'structlibsemigroups_1_1ActionTraits.html': [27, 1],
 'structlibsemigroups_1_1BooleanOne.html': [12, 1, 0, 0, 1, 0],
 'structlibsemigroups_1_1BooleanPlus.html': [12, 1, 0, 0, 1, 1],
 'structlibsemigroups_1_1BooleanProd.html': [12, 1, 0, 0, 1, 2],
 'structlibsemigroups_1_1BooleanZero.html': [12, 1, 0, 0, 1, 3],
 'structlibsemigroups_1_1Complexity.html': [10, 5, 1],
 'structlibsemigroups_1_1Complexity_3_01BMat8_01_4.html': [10, 3, 0],
 'structlibsemigroups_1_1Complexity_3_01HPCombi_1_1BMat8_01_4.html': [10, 5, 0],
 'structlibsemigroups_1_1Complexity_3_01Mat_00_01std_1_1enable__if__t_3_01IsMatrix_3_01Mat_01_4_01_4_01_4.html': [10,
                                                                                                                  4,
                                                                                                                  0],
 'structlibsemigroups_1_1Complexity_3_01PBR_01_4.html': [10, 6, 0],
 'structlibsemigroups_1_1Degree.html': [10, 5, 3],
 'structlibsemigroups_1_1Degree_3_01BMat8_01_4.html': [10, 3, 1],
 'structlibsemigroups_1_1Degree_3_01HPCombi_1_1BMat8_01_4.html': [10, 5, 2],
 'structlibsemigroups_1_1Degree_3_01Mat_00_01std_1_1enable__if__t_3_01IsMatrix_3_01Mat_01_4_01_4_01_4.html': [10,
                                                                                                              4,
                                                                                                              1],
 'structlibsemigroups_1_1Degree_3_01PBR_01_4.html': [10, 6, 1],
 'structlibsemigroups_1_1Dot_1_1Edge.html': [23, 0, 0],
 'structlibsemigroups_1_1Dot_1_1Node.html': [23, 0, 1],
 'structlibsemigroups_1_1EqualTo.html': [10, 1, 0],
 'structlibsemigroups_1_1FroidurePinTraits.html': [31, 2],
 'structlibsemigroups_1_1Hash.html': [10, 1, 1],
 'structlibsemigroups_1_1Hash_3_01Mat_00_01std_1_1enable__if__t_3_01IsMatrix_3_01Mat_01_4_01_4_01_4.html': [10,
                                                                                                            4,
                                                                                                            2],
 'structlibsemigroups_1_1Hash_3_01PBR_01_4.html': [10, 6, 2],
 'structlibsemigroups_1_1ImageLeftAction.html': [10, 0, 2],
 'structlibsemigroups_1_1ImageLeftAction_3_01BMat8_00_01BMat8_01_4.html': [10,
                                                                           3,
                                                                           2],
 'structlibsemigroups_1_1ImageLeftAction_3_01HPCombi_1_1BMat8_00_01HPCombi_1_1BMat8_01_4.html': [10,
                                                                                                 5,
                                                                                                 4],
 'structlibsemigroups_1_1ImageLeftAction_3_01HPCombi_1_1PPerm16_00_01HPCombi_1_1PPerm16_01_4.html': [10,
                                                                                                     5,
                                                                                                     5],
 'structlibsemigroups_1_1ImageLeftAction_3_01HPCombi_1_1Transf16_00_01HPCombi_1_1Vect16_01_4.html': [10,
                                                                                                     5,
                                                                                                     6],
 'structlibsemigroups_1_1ImageLeftAction_3_01Mat_00_01Container_01_4.html': [10,
                                                                             2,
                                                                             0],
 'structlibsemigroups_1_1ImageRightAction.html': [10, 5, 8],
 'structlibsemigroups_1_1ImageRightAction_3_01BMat8_00_01BMat8_01_4.html': [10,
                                                                            3,
                                                                            3],
 'structlibsemigroups_1_1ImageRightAction_3_01HPCombi_1_1BMat8_00_01HPCombi_1_1BMat8_01_4.html': [10,
                                                                                                  5,
                                                                                                  7],
 'structlibsemigroups_1_1ImageRightAction_3_01HPCombi_1_1PPerm16_00_01HPCombi_1_1PPerm16_01_4.html': [10,
                                                                                                      5,
                                                                                                      9],
 'structlibsemigroups_1_1ImageRightAction_3_01HPCombi_1_1Transf16_00_01HPCombi_1_1PTransf16_01_4.html': [10,
                                                                                                         5,
                                                                                                         10],
 'structlibsemigroups_1_1ImageRightAction_3_01Mat_00_01BitSet_3_01N_01_4_01_4.html': [10,
                                                                                      2,
                                                                                      1],
 'structlibsemigroups_1_1ImageRightAction_3_01Mat_00_01Container_01_4.html': [10,
                                                                              2,
                                                                              2],
 'structlibsemigroups_1_1IncreaseDegree.html': [10, 0, 4],
 'structlibsemigroups_1_1IncreaseDegree_3_01BMat8_01_4.html': [10, 3, 4],
 'structlibsemigroups_1_1IncreaseDegree_3_01HPCombi_1_1BMat8_01_4.html': [10,
                                                                          5,
                                                                          11],
 'structlibsemigroups_1_1IncreaseDegree_3_01Mat_00_01std_1_1enable__if__t_3_01IsMatrix_3_01Mat_01_4_01_4_01_4.html': [10,
                                                                                                                      4,
                                                                                                                      3],
 'structlibsemigroups_1_1IncreaseDegree_3_01PBR_01_4.html': [10, 6, 3],
 'structlibsemigroups_1_1IntegerOne.html': [12, 1, 0, 1, 0],
 'structlibsemigroups_1_1IntegerPlus.html': [12, 1, 0, 1, 1],
 'structlibsemigroups_1_1IntegerProd.html': [12, 1, 0, 1, 2],
 'structlibsemigroups_1_1IntegerZero.html': [12, 1, 0, 1, 3],
 'structlibsemigroups_1_1Inverse.html': [10, 0, 5],
 'structlibsemigroups_1_1Inverse_3_01BMat8_01_4.html': [10, 3, 5],
 'structlibsemigroups_1_1Inverse_3_01HPCombi_1_1BMat8_01_4.html': [10, 5, 12],
 'structlibsemigroups_1_1Inverse_3_01HPCombi_1_1Perm16_01_4.html': [10, 5, 13],
 'structlibsemigroups_1_1KoniecznyTraits.html': [34, 1]};

