/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
const None = null;
var NAVTREE = 
[['libsemigroups',
  'index.html#libsemigroups',
  [['What is libsemigroups?', 'index.html#what-is-libsemigroups', None],
   ['Design principles', 'index.html#design-principles', None],
   ['How to use libsemigroups', 'index.html#how-to-use-libsemigroups', None],
   ['Installation', 'index.html#installation', None],
   ['Issues', 'index.html#issues', None],
   ['Dependencies', 'index.html#dependencies', None],
   ['Acknowledgements', 'index.html#acknowledgements', None]]],
 ['Library Info', '_HEADING_', None],
 ['Authors', 'md_authors.html', None],
 ['Bibliography', 'citelist.html', None],
 ['Changelog - version 3', 'md_changelog-v3.html', None],
 ['Changelog - version 2', 'md_changelog-v2.html', None],
 ['Changelog - version 1', 'md_changelog-v1.html', None],
 ['Deprecation', 'md_deprecate.html', None],
 ['Installation', 'md_install.html', None],
 ['Data structures', '_HEADING_', None],
 ['Adapters',
  'group__adapters__group.html',
  [['No default implementation',
    None,
    [['Complexity', 'structlibsemigroups_1_1_complexity.html', None],
     ['Degree', 'structlibsemigroups_1_1_degree.html', None],
     ['ImageLeftAction',
      'structlibsemigroups_1_1_image_left_action.html',
      None],
     ['ImageRightAction',
      'structlibsemigroups_1_1_image_right_action.html',
      None],
     ['IncreaseDegree', 'structlibsemigroups_1_1_increase_degree.html', None],
     ['Inverse', 'structlibsemigroups_1_1_inverse.html', None],
     ['Lambda', 'structlibsemigroups_1_1_lambda.html', None],
     ['LambdaValue', 'structlibsemigroups_1_1_lambda_value.html', None],
     ['One', 'structlibsemigroups_1_1_one.html', None],
     ['Product', 'structlibsemigroups_1_1_product.html', None],
     ['Rho', 'structlibsemigroups_1_1_rho.html', None],
     ['RhoValue', 'structlibsemigroups_1_1_rho_value.html', None]]],
   ['Default implementation',
    None,
    [['EqualTo', 'structlibsemigroups_1_1_equal_to.html', None],
     ['Hash', 'structlibsemigroups_1_1_hash.html', None],
     ['Less', 'structlibsemigroups_1_1_less.html', None],
     ['OnTuples', 'structlibsemigroups_1_1_on_tuples.html', None],
     ['OnSets', 'structlibsemigroups_1_1_on_sets.html', None],
     ['RankState', 'classlibsemigroups_1_1_rank_state.html', None],
     ['Swap', 'structlibsemigroups_1_1_swap.html', None]]],
   ['Adapters for BMat',
    'group__adapters__bmat__group.html',
    [['ImageLeftAction',
      'structlibsemigroups_1_1_image_left_action_3_01_mat_00_01_container_01_4.html',
      None],
     ['ImageRightAction (BitSet)',
      'structlibsemigroups_1_1_image_right_action_3_01_mat_00_01_bit_set_3_01_n_01_4_01_4.html',
      None],
     ['ImageRightAction (Container)',
      'structlibsemigroups_1_1_image_right_action_3_01_mat_00_01_container_01_4.html',
      None],
     ['Lambda',
      'structlibsemigroups_1_1_lambda_3_01_mat_00_01_container_01_4.html',
      None],
     ['LambdaValue',
      'structlibsemigroups_1_1_lambda_value_3_01_mat_01_4.html',
      None],
     ['Rank',
      'structlibsemigroups_1_1_rank_3_01_mat_00_01_rank_state_3_01_mat_01_4_01_4.html',
      None],
     ['RankState',
      'classlibsemigroups_1_1_rank_state_3_01_mat_01_4.html',
      None],
     ['Rho',
      'structlibsemigroups_1_1_rho_3_01_mat_00_01_container_01_4.html',
      None],
     ['RhoValue',
      'structlibsemigroups_1_1_rho_value_3_01_mat_01_4.html',
      None]]],
   ['Adapters for BMat8',
    'group__adapters__bmat8__group.html',
    [['Complexity',
      'structlibsemigroups_1_1_complexity_3_01_b_mat8_01_4.html',
      None],
     ['Degree', 'structlibsemigroups_1_1_degree_3_01_b_mat8_01_4.html', None],
     ['ImageLeftAction',
      'structlibsemigroups_1_1_image_left_action_3_01_b_mat8_00_01_b_mat8_01_4.html',
      None],
     ['ImageRightAction',
      'structlibsemigroups_1_1_image_right_action_3_01_b_mat8_00_01_b_mat8_01_4.html',
      None],
     ['IncreaseDegree',
      'structlibsemigroups_1_1_increase_degree_3_01_b_mat8_01_4.html',
      None],
     ['Inverse', 'structlibsemigroups_1_1_inverse_3_01_b_mat8_01_4.html', None],
     ['Lambda',
      'structlibsemigroups_1_1_lambda_3_01_b_mat8_00_01_b_mat8_01_4.html',
      None],
     ['LambdaValue',
      'structlibsemigroups_1_1_lambda_value_3_01_b_mat8_01_4.html',
      None],
     ['One', 'structlibsemigroups_1_1_one_3_01_b_mat8_01_4.html', None],
     ['Product', 'structlibsemigroups_1_1_product_3_01_b_mat8_01_4.html', None],
     ['Rank', 'structlibsemigroups_1_1_rank_3_01_b_mat8_01_4.html', None],
     ['Rho',
      'structlibsemigroups_1_1_rho_3_01_b_mat8_00_01_b_mat8_01_4.html',
      None],
     ['RhoValue',
      'structlibsemigroups_1_1_rho_value_3_01_b_mat8_01_4.html',
      None]]],
   ['Adapters for other matrices',
    'group__adapters__matrix__group.html',
    [['Complexity',
      'structlibsemigroups_1_1_complexity_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html',
      None],
     ['Degree',
      'structlibsemigroups_1_1_degree_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html',
      None],
     ['Hash',
      'structlibsemigroups_1_1_hash_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html',
      None],
     ['IncreaseDegree',
      'structlibsemigroups_1_1_increase_degree_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html',
      None],
     ['One',
      'structlibsemigroups_1_1_one_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html',
      None],
     ['Product',
      'structlibsemigroups_1_1_product_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html',
      None]]],
   ['Adapters for HPCombi',
    'group__adapters__hpcombi__group.html',
    [['Complexity (BMat8)',
      'structlibsemigroups_1_1_complexity_3_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['Complexity (PTransf16)',
      'structlibsemigroups_1_1_complexity_3_01_t_p_transf16_subclass_00_01std_1_1enable__if__t_3_01std_62333fd2aaa81016b72e36b1c158a5cc.html',
      None],
     ['Degree (BMat8)',
      'structlibsemigroups_1_1_degree_3_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['Degree (PTransf16)',
      'structlibsemigroups_1_1_degree_3_01_t_p_transf16_subclass_00_01std_1_1enable__if__t_3_01std_1_1ie14a4836fcaa250902df94f278d1ee3e.html',
      None],
     ['ImageLeftAction (BMat8)',
      'structlibsemigroups_1_1_image_left_action_3_01_h_p_combi_1_1_b_mat8_00_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['ImageLeftAction (PPerm16)',
      'structlibsemigroups_1_1_image_left_action_3_01_h_p_combi_1_1_p_perm16_00_01_h_p_combi_1_1_p_perm16_01_4.html',
      None],
     ['ImageLeftAction (Transf16)',
      'structlibsemigroups_1_1_image_left_action_3_01_h_p_combi_1_1_transf16_00_01_h_p_combi_1_1_vect16_01_4.html',
      None],
     ['ImageRightAction (BMat8)',
      'structlibsemigroups_1_1_image_right_action_3_01_h_p_combi_1_1_b_mat8_00_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['ImageRightAction (Perm16)',
      'structlibsemigroups_1_1_image_right_action_3_01_h_p_combi_1_1_perm16_00_01_t_int_type_00_01std_1238ac09119ee152a24e6f98356538cb5.html',
      None],
     ['ImageRightAction (PPerm16)',
      'structlibsemigroups_1_1_image_right_action_3_01_h_p_combi_1_1_p_perm16_00_01_h_p_combi_1_1_p_perm16_01_4.html',
      None],
     ['ImageRightAction (Transf16)',
      'structlibsemigroups_1_1_image_right_action_3_01_h_p_combi_1_1_transf16_00_01_h_p_combi_1_1_p_transf16_01_4.html',
      None],
     ['IncreaseDegree',
      'structlibsemigroups_1_1_increase_degree_3_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['Inverse (BMat8)',
      'structlibsemigroups_1_1_inverse_3_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['Inverse (Perm16)',
      'structlibsemigroups_1_1_inverse_3_01_h_p_combi_1_1_perm16_01_4.html',
      None],
     ['Lambda (BMat8)',
      'structlibsemigroups_1_1_lambda_3_01_h_p_combi_1_1_b_mat8_00_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['Lambda (PPerm16)',
      'structlibsemigroups_1_1_lambda_3_01_h_p_combi_1_1_p_perm16_00_01_h_p_combi_1_1_p_perm16_01_4.html',
      None],
     ['Lambda (Transf16)',
      'structlibsemigroups_1_1_lambda_3_01_h_p_combi_1_1_transf16_00_01_h_p_combi_1_1_p_transf16_01_4.html',
      None],
     ['LambdaValue (BMat8)',
      'structlibsemigroups_1_1_lambda_value_3_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['LambdaValue (PPerm16)',
      'structlibsemigroups_1_1_lambda_value_3_01_h_p_combi_1_1_p_perm16_01_4.html',
      None],
     ['LambdaValue (Transf16)',
      'structlibsemigroups_1_1_lambda_value_3_01_h_p_combi_1_1_transf16_01_4.html',
      None],
     ['One (BMat8)',
      'structlibsemigroups_1_1_one_3_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['One (PTransf16)',
      'structlibsemigroups_1_1_one_3_01_t_p_transf16_subclass_00_01std_1_1enable__if__t_3_01std_1_1is__520cc8ea6b19e1b55b58601b08c33bc3.html',
      None],
     ['Product (BMat8)',
      'structlibsemigroups_1_1_product_3_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['Product (PTransf16)',
      'structlibsemigroups_1_1_product_3_01_t_p_transf16_subclass_00_01std_1_1enable__if__t_3_01std_1_1fc0fa38a665bb5b67145388ac9012c4c.html',
      None],
     ['Rank (BMat8)',
      'structlibsemigroups_1_1_rank_3_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['Rank (PTransf16)',
      'structlibsemigroups_1_1_rank_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_01_h_4cf675fa8ee6fcc4791e3b2654577f79.html',
      None],
     ['Rho (BMat8)',
      'structlibsemigroups_1_1_rho_3_01_h_p_combi_1_1_b_mat8_00_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['Rho (PPerm16)',
      'structlibsemigroups_1_1_rho_3_01_h_p_combi_1_1_p_perm16_00_01_h_p_combi_1_1_p_perm16_01_4.html',
      None],
     ['Rho (Transf16)',
      'structlibsemigroups_1_1_rho_3_01_h_p_combi_1_1_transf16_00_01_h_p_combi_1_1_vect16_01_4.html',
      None],
     ['RhoValue (BMat8)',
      'structlibsemigroups_1_1_rho_value_3_01_h_p_combi_1_1_b_mat8_01_4.html',
      None],
     ['RhoValue (PPerm16)',
      'structlibsemigroups_1_1_rho_value_3_01_h_p_combi_1_1_p_perm16_01_4.html',
      None],
     ['RhoValue (Transf16)',
      'structlibsemigroups_1_1_rho_value_3_01_h_p_combi_1_1_transf16_01_4.html',
      None],
     ['Swap',
      'structlibsemigroups_1_1_swap_3_01_t_p_transf16_subclass_00_01std_1_1enable__if__t_3_01std_1_1is_dbd89545857f7e9f53ff2b2b6e997e30.html',
      None]]],
   ['Adapters for PBR',
    'group__adapters__pbr__group.html',
    [['Complexity',
      'structlibsemigroups_1_1_complexity_3_01_p_b_r_01_4.html',
      None],
     ['Degree', 'structlibsemigroups_1_1_degree_3_01_p_b_r_01_4.html', None],
     ['Hash', 'structlibsemigroups_1_1_hash_3_01_p_b_r_01_4.html', None],
     ['IncreaseDegree',
      'structlibsemigroups_1_1_increase_degree_3_01_p_b_r_01_4.html',
      None],
     ['One', 'structlibsemigroups_1_1_one_3_01_p_b_r_01_4.html', None],
     ['Product',
      'structlibsemigroups_1_1_product_3_01_p_b_r_01_4.html',
      None]]]]],
 ['Constants', 'group__constants__group.html', None],
 ['Elements',
  'group__elements__group.html',
  [['Bipartitions',
    'group__bipart__group.html',
    [['The Bipartition class', 'classlibsemigroups_1_1_bipartition.html', None],
     ['The Blocks class', 'classlibsemigroups_1_1_blocks.html', None],
     ['Bipartition helper functions',
      'namespacelibsemigroups_1_1bipartition.html',
      None],
     ['Blocks helper functions', 'namespacelibsemigroups_1_1blocks.html', None],
     ['make<Biparition>', 'group__make__bipart__group.html', None],
     ['make<Blocks>', 'group__make__blocks__group.html', None]]],
   ['Matrices',
    'group__matrix__group.html',
    [['Over specific semirings',
      None,
      [['Boolean matrices',
        'group__bmat__index__group.html',
        [['BMat8',
          'group__bmat8__group.html',
          [['The BMat8 class', 'classlibsemigroups_1_1_b_mat8.html', None],
           ['BMat8 helper functions',
            'namespacelibsemigroups_1_1bmat8.html',
            None]]],
         ['BMat',
          'group__bmat__group.html',
          [['BooleanOne', 'structlibsemigroups_1_1_boolean_one.html', None],
           ['BooleanPlus', 'structlibsemigroups_1_1_boolean_plus.html', None],
           ['BooleanProd', 'structlibsemigroups_1_1_boolean_prod.html', None],
           ['BooleanZero',
            'structlibsemigroups_1_1_boolean_zero.html',
            None]]]]],
       ['Integer matrices',
        'group__intmat__group.html',
        [['IntegerOne', 'structlibsemigroups_1_1_integer_one.html', None],
         ['IntegerPlus', 'structlibsemigroups_1_1_integer_plus.html', None],
         ['IntegerProd', 'structlibsemigroups_1_1_integer_prod.html', None],
         ['IntegerZero', 'structlibsemigroups_1_1_integer_zero.html', None]]],
       ['Max-plus matrices',
        'group__maxplusmat__group.html',
        [['MaxPlusPlus', 'structlibsemigroups_1_1_max_plus_plus.html', None],
         ['MaxPlusProd', 'structlibsemigroups_1_1_max_plus_prod.html', None],
         ['MaxPlusZero', 'structlibsemigroups_1_1_max_plus_zero.html', None]]],
       ['Min-plus matrices',
        'group__minplusmat__group.html',
        [['MinPlusPlus', 'structlibsemigroups_1_1_min_plus_plus.html', None],
         ['MinPlusProd', 'structlibsemigroups_1_1_min_plus_prod.html', None],
         ['MinPlusZero', 'structlibsemigroups_1_1_min_plus_zero.html', None]]],
       ['Truncated max-plus matrices',
        'group__maxplustruncmat__group.html',
        [['MaxPlusTruncProd',
          'structlibsemigroups_1_1_max_plus_trunc_prod.html',
          None],
         ['MaxPlusTruncSemiring',
          'classlibsemigroups_1_1_max_plus_trunc_semiring.html',
          None]]],
       ['Truncated min-plus matrices',
        'group__minplustruncmat__group.html',
        [['MinPlusTruncProd',
          'structlibsemigroups_1_1_min_plus_trunc_prod.html',
          None],
         ['MinPlusTruncSemiring',
          'classlibsemigroups_1_1_min_plus_trunc_semiring.html',
          None]]],
       ['Matrices over ℕ/(t = t + p)',
        'group__ntpmat__group.html',
        [['NTPPlus', 'structlibsemigroups_1_1_n_t_p_plus.html', None],
         ['NTPProd', 'structlibsemigroups_1_1_n_t_p_prod.html', None],
         ['NTPSemiring', 'classlibsemigroups_1_1_n_t_p_semiring.html', None]]],
       ['Projective max-plus matrices',
        'group__projmaxplus__group.html',
        None]]],
     ['Over arbitrary semirings',
      None,
      [['DynamicMatrix (compile-time)',
        'classlibsemigroups_1_1_dynamic_matrix_3_01_plus_op_00_01_prod_op_00_01_zero_op_00_01_one_op_00_01_scalar_01_4.html',
        None],
       ['DynamicMatrix (run-time)',
        'classlibsemigroups_1_1_dynamic_matrix_3_01_semiring_00_01_scalar_01_4.html',
        None],
       ['StaticMatrix', 'classlibsemigroups_1_1_static_matrix.html', None]]],
     ['Row views',
      None,
      [['DynamicRowView (compile-time)',
        'classlibsemigroups_1_1_dynamic_row_view_3_01_plus_op_00_01_prod_op_00_01_zero_op_00_01_one_op_00_01_scalar_01_4.html#DynamicRowViewStaticArith',
        None],
       ['DynamicRowView (run-time)',
        'classlibsemigroups_1_1_dynamic_row_view_3_01_semiring_00_01_scalar_01_4.html#DynamicRowViewDynamicArith',
        None],
       ['StaticRowView', 'classlibsemigroups_1_1_static_row_view.html', None]]],
     ['make<Matrix>', 'group__make__matrix__group.html', None]]],
   ['Partitioned binary relations (PBRs)',
    'group__pbr__group.html',
    [['PBR', 'classlibsemigroups_1_1_p_b_r.html', None],
     ['PBR helper functions', 'namespacelibsemigroups_1_1pbr.html', None],
     ['make<PBR>', 'group__make__pbr__group.html', None]]],
   ['Transformations',
    'group__transf__group.html',
    [['DynamicPTransf', 'classlibsemigroups_1_1_dynamic_p_transf.html', None],
     ['Perm', 'classlibsemigroups_1_1_perm.html', None],
     ['PPerm', 'classlibsemigroups_1_1_p_perm.html', None],
     ['PTransfBase', 'classlibsemigroups_1_1_p_transf_base.html', None],
     ['StaticPTransf', 'classlibsemigroups_1_1_static_p_transf.html', None],
     ['Transf', 'classlibsemigroups_1_1_transf.html', None],
     ['make<Transf>', 'group__make__transf__group.html', None],
     ['make<PPerm>', 'group__make__pperm__group.html', None],
     ['make<Perm>', 'group__make__perm__group.html', None]]]]],
 ['Exceptions',
  'group__exception__group.html',
  [['LibsemigroupsException',
    'structlibsemigroups_1_1_libsemigroups_exception.html',
    None]]],
 ['Orders',
  'group__orders__group.html',
  [['LexicographicalCompare',
    'structlibsemigroups_1_1_lexicographical_compare.html',
    None],
   ['RecursivePathCompare',
    'structlibsemigroups_1_1_recursive_path_compare.html',
    None],
   ['ShortLexCompare',
    'structlibsemigroups_1_1_short_lex_compare.html',
    None]]],
 ['Presentations',
  'group__presentations__group.html',
  [['The Presentation class', 'classlibsemigroups_1_1_presentation.html', None],
   ['The InversePresentation class',
    'classlibsemigroups_1_1_inverse_presentation.html',
    None],
   ['Helper functions', 'namespacelibsemigroups_1_1presentation.html', None],
   ['Examples',
    'namespacelibsemigroups_1_1presentation_1_1examples.html',
    None],
   ['to<Presentation>', 'group__to__presentation__group.html', None],
   ['to<InversePresentation>',
    'group__to__inverse__presentation__group.html',
    None],
   ['Obviously infinite',
    'group__obvinf__group.html',
    [['IsObviouslyInfinite',
      'classlibsemigroups_1_1_is_obviously_infinite.html',
      None]]]]],
 ['Ranges',
  'group__ranges__group.html',
  [['Random', 'structlibsemigroups_1_1_random.html', None]]],
 ['Suffix trees',
  'group__ukkonen__group.html',
  [['The Ukkonen class',
    'classlibsemigroups_1_1_ukkonen.html',
    [['The Node class', 'structlibsemigroups_1_1_ukkonen_1_1_node.html', None],
     ['The State class',
      'structlibsemigroups_1_1_ukkonen_1_1_state.html',
      None]]],
   ['Ukkonen helper functions',
    'namespacelibsemigroups_1_1ukkonen.html',
    None]]],
 ['The `make` function', 'group__make__group.html', None],
 ['The `to` function', 'group__to__group.html', None],
 ['Tries',
  'group__aho__corasick__group.html',
  [['The AhoCorasick class', 'classlibsemigroups_1_1_aho_corasick.html', None],
   ['AhoCorasick helper functions',
    'namespacelibsemigroups_1_1aho__corasick.html',
    None]]],
 ['Enums + Types',
  'group__types__group.html',
  [['SmallestInteger', 'structlibsemigroups_1_1_smallest_integer.html', None]]],
 ['Visualisation',
  'group__dot__group.html',
  [['The Dot class',
    'classlibsemigroups_1_1_dot.html',
    [['The Edge class', 'structlibsemigroups_1_1_dot_1_1_edge.html', None],
     ['The Node class', 'structlibsemigroups_1_1_dot_1_1_node.html', None]]]]],
 ['Word graphs',
  'group__word__graph__group.html',
  [['The Forest class', 'classlibsemigroups_1_1_forest.html', None],
   ['The Gabow class', 'classlibsemigroups_1_1_gabow.html', None],
   ['The Joiner class', 'classlibsemigroups_1_1_joiner.html', None],
   ['The Meeter class', 'classlibsemigroups_1_1_meeter.html', None],
   ['The Paths class', 'classlibsemigroups_1_1_paths.html', None],
   ['The WordGraph class', 'classlibsemigroups_1_1_word_graph.html', None],
   ['Forest helper functions', 'namespacelibsemigroups_1_1forest.html', None],
   ['Paths helper functions', 'namespacelibsemigroups_1_1paths.html', None],
   ['WordGraph helper functions',
    'namespacelibsemigroups_1_1word__graph.html',
    None],
   ['make<Forest>', 'group__make__forest__group.html', None],
   ['make<WordGraph>', 'group__make__word__graph__group.html', None]]],
 ['Words',
  'group__words__group.html',
  [['The StringRange class', 'classlibsemigroups_1_1_string_range.html', None],
   ['The WordRange class', 'classlibsemigroups_1_1_word_range.html', None],
   ['The ToString class', 'classlibsemigroups_1_1_to_string.html', None],
   ['The ToWord class', 'classlibsemigroups_1_1_to_word.html', None],
   ['Functions for words and strings',
    'namespacelibsemigroups_1_1words.html',
    None],
   ['Literals', 'namespacelibsemigroups_1_1literals.html', None]]],
 ['Main Algorithms', '_HEADING_', None],
 ['Actions',
  'group__action__group.html',
  [['The Action class', 'classlibsemigroups_1_1_action.html', None],
   ['The ActionTraits class',
    'structlibsemigroups_1_1_action_traits.html',
    None]]],
 ['Common congruence helper function',
  'group__cong__common__helpers__group.html',
  [['Add generating pairs',
    'group__cong__common__helpers__add__pair__group.html',
    None],
   ['Containment', 'group__cong__common__helpers__contains__group.html', None],
   ['Reduce a word', 'group__cong__common__helpers__reduce__group.html', None],
   ['Partitioning',
    'group__cong__common__helpers__partition__group.html',
    None]]],
 ['Congruence',
  'group__congruence__group.html',
  [['The Congruence class',
    'group__congruence__class__group.html',
    [['Member types', 'group__congruence__class__mem__types__group.html', None],
     ['Constructors + Initializers',
      'group__congruence__class__init__group.html',
      None],
     ['Settings', 'group__congruence__class__settings__group.html', None],
     ['Common member functions',
      'group__congruence__class__intf__group.html',
      None],
     ['Accessors', 'group__congruence__class__accessors__group.html', None]]],
   ['Congruence helper functions',
    'group__congruence__helpers__group.html',
    None],
   ['to<Congruence>', 'group__to__cong__group.html', None]]],
 ['Core classes',
  'group__core__classes__group.html',
  [['Reporter', 'classlibsemigroups_1_1_reporter.html', None],
   ['ReportGuard', 'structlibsemigroups_1_1_report_guard.html', None],
   ['Runner', 'classlibsemigroups_1_1_runner.html', None]]],
 ['Froidure-Pin',
  'group__froidure__pin__group.html',
  [['The FroidurePin class', 'classlibsemigroups_1_1_froidure_pin.html', None],
   ['The FroidurePinBase class',
    'classlibsemigroups_1_1_froidure_pin_base.html',
    None],
   ['The FroidurePinTraits class',
    'structlibsemigroups_1_1_froidure_pin_traits.html',
    None],
   ['FroidurePin helper functions',
    'namespacelibsemigroups_1_1froidure__pin.html',
    None],
   ['to<FroidurePin>', 'group__to__froidure__pin__group.html', None],
   ['make<FroidurePin>', 'group__make__froidure__pin__group.html', None]]],
 ['Kambites',
  'group__kambites__group.html',
  [['The Kambites class',
    'group__kambites__class__group.html',
    [['Member types', 'group__kambites__class__mem__types__group.html', None],
     ['Constructors + Initializers',
      'group__kambites__class__init__group.html',
      None],
     ['Common member functions',
      'group__kambites__class__intf__group.html',
      None],
     ['Accessors', 'group__kambites__class__accessors__group.html', None]]],
   ['Kambites helper functions',
    'group__kambites__helpers__group.html',
    None]]],
 ['Knuth-Bendix',
  'group__knuth__bendix__group.html',
  [['The KnuthBendix class',
    'group__knuth__bendix__class__group.html',
    [['Member types',
      'group__knuth__bendix__class__mem__types__group.html',
      None],
     ['Constructors + Initializers',
      'group__knuth__bendix__class__init__group.html',
      None],
     ['Settings', 'group__knuth__bendix__class__settings__group.html', None],
     ['Common member functions',
      'group__knuth__bendix__class__intf__group.html',
      None],
     ['Accessors',
      'group__knuth__bendix__class__accessors__group.html',
      None]]],
   ['Knuth-Bendix helper functions',
    'group__knuth__bendix__helpers__group.html',
    None],
   ['to<KnuthBendix>', 'group__to__knuth__bendix__group.html', None]]],
 ['Konieczny',
  'group__konieczny__group.html',
  [['The Konieczny class', 'classlibsemigroups_1_1_konieczny.html', None],
   ['The KoniecznyTraits class',
    'structlibsemigroups_1_1_konieczny_traits.html',
    None],
   ['The DClass class',
    'classlibsemigroups_1_1_konieczny_1_1_d_class.html',
    None],
   ['Konieczny helper functions',
    'namespacelibsemigroups_1_1konieczny.html',
    None],
   ['make<Konieczny>', 'group__make__konieczny__group.html', None]]],
 ['Low Index Congruences',
  'group__sims__group.html',
  [['Classes',
    'group__sims__group.html#nested-classes',
    [['MinimalRepOrc', 'classlibsemigroups_1_1_minimal_rep_orc.html', None],
     ['RepOrc', 'classlibsemigroups_1_1_rep_orc.html', None],
     ['Sims1', 'classlibsemigroups_1_1_sims1.html', None],
     ['Sims2', 'classlibsemigroups_1_1_sims2.html', None],
     ['SimsRefinerFaithful',
      'classlibsemigroups_1_1_sims_refiner_faithful.html',
      None],
     ['SimsRefinerIdeals',
      'classlibsemigroups_1_1_sims_refiner_ideals.html',
      None],
     ['SimsSettings', 'classlibsemigroups_1_1_sims_settings.html', None],
     ['SimsStats', 'classlibsemigroups_1_1_sims_stats.html', None]]],
   ['Helper functions', 'namespacelibsemigroups_1_1sims.html', None]]],
 ['Radoszewski-Rytter', 'group__freeband__group.html', None],
 ['Schreier-Sims',
  'group__schreier__sims__group.html',
  [['The SchreierSims class',
    'classlibsemigroups_1_1_schreier_sims.html',
    None],
   ['The SchreierSims Traits class',
    'structlibsemigroups_1_1_schreier_sims_traits.html',
    None],
   ['SchreierSims helper functions',
    'namespacelibsemigroups_1_1schreier__sims.html',
    None]]],
 ['Stephen',
  'group__stephen__group.html',
  [['The Stephen class', 'classlibsemigroups_1_1_stephen.html', None],
   ['Stephen helper functions',
    'namespacelibsemigroups_1_1stephen.html',
    None]]],
 ['Todd-Coxeter',
  'group__todd__coxeter__group.html',
  [['The ToddCoxeter class',
    'group__todd__coxeter__class__group.html',
    [['Instrumenting Todd-Coxeter', 'md_todd-coxeter-report.html', None],
     ['Member types',
      'group__todd__coxeter__class__mem__types__group.html',
      [['The options nested struct',
        'structlibsemigroups_1_1_todd_coxeter_1_1options.html',
        None]]],
     ['Constructors + Initializers',
      'group__todd__coxeter__class__init__group.html',
      None],
     ['Settings', 'group__todd__coxeter__class__settings__group.html', None],
     ['Common functions',
      'group__todd__coxeter__class__intf__group.html',
      None],
     ['Accessors', 'group__todd__coxeter__class__accessors__group.html', None],
     ['Modifiers', 'group__todd__coxeter__class__mod__group.html', None],
     ['Word -> index',
      'group__todd__coxeter__class__word__index__group.html',
      None],
     ['Index -> word',
      'group__todd__coxeter__class__index__word__group.html',
      None]]],
   ['Todd-Coxeter helper functions',
    'group__todd__coxeter__helpers__group.html',
    None],
   ['to<ToddCoxeter>', 'group__to__todd__coxeter__group.html', None]]]];


var NAVTREEINDEX =
[
"_HEADING_",
"structlibsemigroups_1_1_lambda_3_01_mat_00_01_container_01_4.html"
];

var SYNCONMSG = 'click to disable panel synchronization';
var SYNCOFFMSG = 'click to enable panel synchronization';