var NAVTREEINDEX0 = 
{'_HEADING_': [24],
 'citelist.html': [3],
 'classlibsemigroups_1_1_action.html': [25, 0],
 'classlibsemigroups_1_1_aho_corasick.html': [19, 0],
 'classlibsemigroups_1_1_b_mat8.html': [11, 1, 0, 0, 0, 0],
 'classlibsemigroups_1_1_bipartition.html': [11, 0, 0],
 'classlibsemigroups_1_1_blocks.html': [11, 0, 1],
 'classlibsemigroups_1_1_dot.html': [21, 0],
 'classlibsemigroups_1_1_dynamic_matrix_3_01_plus_op_00_01_prod_op_00_01_zero_op_00_01_one_op_00_01_scalar_01_4.html': [11,
                                                                                                                        1,
                                                                                                                        1,
                                                                                                                        0],
 'classlibsemigroups_1_1_dynamic_matrix_3_01_semiring_00_01_scalar_01_4.html': [11,
                                                                                1,
                                                                                1,
                                                                                1],
 'classlibsemigroups_1_1_dynamic_p_transf.html': [11, 3, 0],
 'classlibsemigroups_1_1_dynamic_row_view_3_01_plus_op_00_01_prod_op_00_01_zero_op_00_01_one_op_00_01_scalar_01_4.html#DynamicRowViewStaticArith': [11,
                                                                                                                                                    1,
                                                                                                                                                    2,
                                                                                                                                                    0],
 'classlibsemigroups_1_1_dynamic_row_view_3_01_semiring_00_01_scalar_01_4.html#DynamicRowViewDynamicArith': [11,
                                                                                                             1,
                                                                                                             2,
                                                                                                             1],
 'classlibsemigroups_1_1_forest.html': [22, 0],
 'classlibsemigroups_1_1_froidure_pin.html': [29, 0],
 'classlibsemigroups_1_1_froidure_pin_base.html': [29, 1],
 'classlibsemigroups_1_1_gabow.html': [22, 1],
 'classlibsemigroups_1_1_inverse_presentation.html': [15, 1],
 'classlibsemigroups_1_1_is_obviously_infinite.html': [15, 6, 0],
 'classlibsemigroups_1_1_joiner.html': [22, 2],
 'classlibsemigroups_1_1_konieczny.html': [32, 0],
 'classlibsemigroups_1_1_konieczny_1_1_d_class.html': [32, 2],
 'classlibsemigroups_1_1_max_plus_trunc_semiring.html': [11, 1, 0, 4, 1],
 'classlibsemigroups_1_1_meeter.html': [22, 3],
 'classlibsemigroups_1_1_min_plus_trunc_semiring.html': [11, 1, 0, 5, 1],
 'classlibsemigroups_1_1_minimal_rep_orc.html': [33, 0, 0],
 'classlibsemigroups_1_1_n_t_p_semiring.html': [11, 1, 0, 6, 2],
 'classlibsemigroups_1_1_p_b_r.html': [11, 2, 0],
 'classlibsemigroups_1_1_p_perm.html': [11, 3, 2],
 'classlibsemigroups_1_1_p_transf_base.html': [11, 3, 3],
 'classlibsemigroups_1_1_paths.html': [22, 4],
 'classlibsemigroups_1_1_perm.html': [11, 3, 1],
 'classlibsemigroups_1_1_presentation.html': [15, 0],
 'classlibsemigroups_1_1_rank_state.html': [9, 1, 5],
 'classlibsemigroups_1_1_rank_state_3_01_mat_01_4.html': [9, 2, 6],
 'classlibsemigroups_1_1_rep_orc.html': [33, 0, 1],
 'classlibsemigroups_1_1_reporter.html': [28, 0],
 'classlibsemigroups_1_1_runner.html': [28, 2],
 'classlibsemigroups_1_1_schreier_sims.html': [35, 0],
 'classlibsemigroups_1_1_sims1.html': [33, 0, 2],
 'classlibsemigroups_1_1_sims2.html': [33, 0, 3],
 'classlibsemigroups_1_1_sims_refiner_faithful.html': [33, 0, 4],
 'classlibsemigroups_1_1_sims_refiner_ideals.html': [33, 0, 5],
 'classlibsemigroups_1_1_sims_settings.html': [33, 0, 6],
 'classlibsemigroups_1_1_sims_stats.html': [33, 0, 7],
 'classlibsemigroups_1_1_static_matrix.html': [11, 1, 1, 2],
 'classlibsemigroups_1_1_static_p_transf.html': [11, 3, 4],
 'classlibsemigroups_1_1_static_row_view.html': [11, 1, 2, 2],
 'classlibsemigroups_1_1_stephen.html': [36, 0],
 'classlibsemigroups_1_1_string_range.html': [23, 0],
 'classlibsemigroups_1_1_to_string.html': [23, 2],
 'classlibsemigroups_1_1_to_word.html': [23, 3],
 'classlibsemigroups_1_1_transf.html': [11, 3, 5],
 'classlibsemigroups_1_1_ukkonen.html': [17, 0],
 'classlibsemigroups_1_1_word_graph.html': [22, 5],
 'classlibsemigroups_1_1_word_range.html': [23, 1],
 'group__action__group.html': [25],
 'group__adapters__bmat8__group.html': [9, 3],
 'group__adapters__bmat__group.html': [9, 2],
 'group__adapters__group.html': [9],
 'group__adapters__hpcombi__group.html': [9, 5],
 'group__adapters__matrix__group.html': [9, 4],
 'group__adapters__pbr__group.html': [9, 6],
 'group__aho__corasick__group.html': [19],
 'group__bipart__group.html': [11, 0],
 'group__bmat8__group.html': [11, 1, 0, 0, 0],
 'group__bmat__group.html': [11, 1, 0, 0, 1],
 'group__bmat__index__group.html': [11, 1, 0, 0],
 'group__cong__common__helpers__add__pair__group.html': [26, 0],
 'group__cong__common__helpers__contains__group.html': [26, 1],
 'group__cong__common__helpers__group.html': [26],
 'group__cong__common__helpers__partition__group.html': [26, 3],
 'group__cong__common__helpers__reduce__group.html': [26, 2],
 'group__congruence__class__accessors__group.html': [27, 0, 4],
 'group__congruence__class__group.html': [27, 0],
 'group__congruence__class__init__group.html': [27, 0, 1],
 'group__congruence__class__intf__group.html': [27, 0, 3],
 'group__congruence__class__mem__types__group.html': [27, 0, 0],
 'group__congruence__class__settings__group.html': [27, 0, 2],
 'group__congruence__group.html': [27],
 'group__congruence__helpers__group.html': [27, 1],
 'group__constants__group.html': [10],
 'group__core__classes__group.html': [28],
 'group__dot__group.html': [21],
 'group__elements__group.html': [11],
 'group__exception__group.html': [12],
 'group__freeband__group.html': [34],
 'group__froidure__pin__group.html': [29],
 'group__intmat__group.html': [11, 1, 0, 1],
 'group__kambites__class__accessors__group.html': [30, 0, 3],
 'group__kambites__class__group.html': [30, 0],
 'group__kambites__class__init__group.html': [30, 0, 1],
 'group__kambites__class__intf__group.html': [30, 0, 2],
 'group__kambites__class__mem__types__group.html': [30, 0, 0],
 'group__kambites__group.html': [30],
 'group__kambites__helpers__group.html': [30, 1],
 'group__knuth__bendix__class__accessors__group.html': [31, 0, 4],
 'group__knuth__bendix__class__group.html': [31, 0],
 'group__knuth__bendix__class__init__group.html': [31, 0, 1],
 'group__knuth__bendix__class__intf__group.html': [31, 0, 3],
 'group__knuth__bendix__class__mem__types__group.html': [31, 0, 0],
 'group__knuth__bendix__class__settings__group.html': [31, 0, 2],
 'group__knuth__bendix__group.html': [31],
 'group__knuth__bendix__helpers__group.html': [31, 1],
 'group__konieczny__group.html': [32],
 'group__make__bipart__group.html': [11, 0, 4],
 'group__make__blocks__group.html': [11, 0, 5],
 'group__make__forest__group.html': [22, 9],
 'group__make__froidure__pin__group.html': [29, 5],
 'group__make__group.html': [13],
 'group__make__konieczny__group.html': [32, 4],
 'group__make__matrix__group.html': [11, 1, 3],
 'group__make__pbr__group.html': [11, 2, 2],
 'group__make__perm__group.html': [11, 3, 8],
 'group__make__pperm__group.html': [11, 3, 7],
 'group__make__transf__group.html': [11, 3, 6],
 'group__make__word__graph__group.html': [22, 10],
 'group__matrix__group.html': [11, 1],
 'group__maxplusmat__group.html': [11, 1, 0, 2],
 'group__maxplustruncmat__group.html': [11, 1, 0, 4],
 'group__minplusmat__group.html': [11, 1, 0, 3],
 'group__minplustruncmat__group.html': [11, 1, 0, 5],
 'group__ntpmat__group.html': [11, 1, 0, 6],
 'group__obvinf__group.html': [15, 6],
 'group__orders__group.html': [14],
 'group__pbr__group.html': [11, 2],
 'group__presentations__group.html': [15],
 'group__projmaxplus__group.html': [11, 1, 0, 7],
 'group__ranges__group.html': [16],
 'group__schreier__sims__group.html': [35],
 'group__sims__group.html': [33],
 'group__sims__group.html#nested-classes': [33, 0],
 'group__stephen__group.html': [36],
 'group__to__cong__group.html': [27, 2],
 'group__to__froidure__pin__group.html': [29, 4],
 'group__to__group.html': [18],
 'group__to__inverse__presentation__group.html': [15, 5],
 'group__to__knuth__bendix__group.html': [31, 2],
 'group__to__presentation__group.html': [15, 4],
 'group__to__todd__coxeter__group.html': [37, 2],
 'group__todd__coxeter__class__accessors__group.html': [37, 0, 4],
 'group__todd__coxeter__class__group.html': [37, 0],
 'group__todd__coxeter__class__index__word__group.html': [37, 0, 7],
 'group__todd__coxeter__class__init__group.html': [37, 0, 1],
 'group__todd__coxeter__class__intf__group.html': [37, 0, 3],
 'group__todd__coxeter__class__mem__types__group.html': [37, 0, 0],
 'group__todd__coxeter__class__mod__group.html': [37, 0, 5],
 'group__todd__coxeter__class__settings__group.html': [37, 0, 2],
 'group__todd__coxeter__class__word__index__group.html': [37, 0, 6],
 'group__todd__coxeter__group.html': [37],
 'group__todd__coxeter__helpers__group.html': [37, 1],
 'group__transf__group.html': [11, 3],
 'group__types__group.html': [20],
 'group__ukkonen__group.html': [17],
 'group__word__graph__group.html': [22],
 'group__words__group.html': [23],
 'index.html#acknowledgements': [0, 6],
 'index.html#dependencies': [0, 5],
 'index.html#design-principles': [0, 1],
 'index.html#how-to-use-libsemigroups': [0, 2],
 'index.html#installation': [0, 3],
 'index.html#issues': [0, 4],
 'index.html#libsemigroups': [0],
 'index.html#what-is-libsemigroups': [0, 0],
 'md_authors.html': [2],
 'md_changelog-v1.html': [6],
 'md_changelog-v2.html': [5],
 'md_changelog-v3.html': [4],
 'md_install.html': [7],
 'namespacelibsemigroups_1_1aho__corasick.html': [19, 1],
 'namespacelibsemigroups_1_1bipartition.html': [11, 0, 2],
 'namespacelibsemigroups_1_1blocks.html': [11, 0, 3],
 'namespacelibsemigroups_1_1bmat8.html': [11, 1, 0, 0, 0, 1],
 'namespacelibsemigroups_1_1forest.html': [22, 6],
 'namespacelibsemigroups_1_1froidure__pin.html': [29, 3],
 'namespacelibsemigroups_1_1konieczny.html': [32, 3],
 'namespacelibsemigroups_1_1literals.html': [23, 5],
 'namespacelibsemigroups_1_1paths.html': [22, 7],
 'namespacelibsemigroups_1_1pbr.html': [11, 2, 1],
 'namespacelibsemigroups_1_1presentation.html': [15, 2],
 'namespacelibsemigroups_1_1presentation_1_1examples.html': [15, 3],
 'namespacelibsemigroups_1_1schreier__sims.html': [35, 2],
 'namespacelibsemigroups_1_1sims.html': [33, 1],
 'namespacelibsemigroups_1_1stephen.html': [36, 1],
 'namespacelibsemigroups_1_1ukkonen.html': [17, 1],
 'namespacelibsemigroups_1_1word__graph.html': [22, 8],
 'namespacelibsemigroups_1_1words.html': [23, 4],
 'structlibsemigroups_1_1_action_traits.html': [25, 1],
 'structlibsemigroups_1_1_boolean_one.html': [11, 1, 0, 0, 1, 0],
 'structlibsemigroups_1_1_boolean_plus.html': [11, 1, 0, 0, 1, 1],
 'structlibsemigroups_1_1_boolean_prod.html': [11, 1, 0, 0, 1, 2],
 'structlibsemigroups_1_1_boolean_zero.html': [11, 1, 0, 0, 1, 3],
 'structlibsemigroups_1_1_complexity.html': [9, 0, 0],
 'structlibsemigroups_1_1_complexity_3_01_b_mat8_01_4.html': [9, 3, 0],
 'structlibsemigroups_1_1_complexity_3_01_h_p_combi_1_1_b_mat8_01_4.html': [9,
                                                                            5,
                                                                            0],
 'structlibsemigroups_1_1_complexity_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html': [9,
                                                                                                                       4,
                                                                                                                       0],
 'structlibsemigroups_1_1_complexity_3_01_p_b_r_01_4.html': [9, 6, 0],
 'structlibsemigroups_1_1_complexity_3_01_t_p_transf16_subclass_00_01std_1_1enable__if__t_3_01std_62333fd2aaa81016b72e36b1c158a5cc.html': [9,
                                                                                                                                           5,
                                                                                                                                           1],
 'structlibsemigroups_1_1_degree.html': [9, 0, 1],
 'structlibsemigroups_1_1_degree_3_01_b_mat8_01_4.html': [9, 3, 1],
 'structlibsemigroups_1_1_degree_3_01_h_p_combi_1_1_b_mat8_01_4.html': [9,
                                                                        5,
                                                                        2],
 'structlibsemigroups_1_1_degree_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html': [9,
                                                                                                                   4,
                                                                                                                   1],
 'structlibsemigroups_1_1_degree_3_01_p_b_r_01_4.html': [9, 6, 1],
 'structlibsemigroups_1_1_degree_3_01_t_p_transf16_subclass_00_01std_1_1enable__if__t_3_01std_1_1ie14a4836fcaa250902df94f278d1ee3e.html': [9,
                                                                                                                                           5,
                                                                                                                                           3],
 'structlibsemigroups_1_1_dot_1_1_edge.html': [21, 0, 0],
 'structlibsemigroups_1_1_dot_1_1_node.html': [21, 0, 1],
 'structlibsemigroups_1_1_equal_to.html': [9, 1, 0],
 'structlibsemigroups_1_1_froidure_pin_traits.html': [29, 2],
 'structlibsemigroups_1_1_hash.html': [9, 1, 1],
 'structlibsemigroups_1_1_hash_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html': [9,
                                                                                                                 4,
                                                                                                                 2],
 'structlibsemigroups_1_1_hash_3_01_p_b_r_01_4.html': [9, 6, 2],
 'structlibsemigroups_1_1_image_left_action.html': [9, 0, 2],
 'structlibsemigroups_1_1_image_left_action_3_01_b_mat8_00_01_b_mat8_01_4.html': [9,
                                                                                  3,
                                                                                  2],
 'structlibsemigroups_1_1_image_left_action_3_01_h_p_combi_1_1_b_mat8_00_01_h_p_combi_1_1_b_mat8_01_4.html': [9,
                                                                                                              5,
                                                                                                              4],
 'structlibsemigroups_1_1_image_left_action_3_01_h_p_combi_1_1_p_perm16_00_01_h_p_combi_1_1_p_perm16_01_4.html': [9,
                                                                                                                  5,
                                                                                                                  5],
 'structlibsemigroups_1_1_image_left_action_3_01_h_p_combi_1_1_transf16_00_01_h_p_combi_1_1_vect16_01_4.html': [9,
                                                                                                                5,
                                                                                                                6],
 'structlibsemigroups_1_1_image_left_action_3_01_mat_00_01_container_01_4.html': [9,
                                                                                  2,
                                                                                  0],
 'structlibsemigroups_1_1_image_right_action.html': [9, 0, 3],
 'structlibsemigroups_1_1_image_right_action_3_01_b_mat8_00_01_b_mat8_01_4.html': [9,
                                                                                   3,
                                                                                   3],
 'structlibsemigroups_1_1_image_right_action_3_01_h_p_combi_1_1_b_mat8_00_01_h_p_combi_1_1_b_mat8_01_4.html': [9,
                                                                                                               5,
                                                                                                               7],
 'structlibsemigroups_1_1_image_right_action_3_01_h_p_combi_1_1_p_perm16_00_01_h_p_combi_1_1_p_perm16_01_4.html': [9,
                                                                                                                   5,
                                                                                                                   9],
 'structlibsemigroups_1_1_image_right_action_3_01_h_p_combi_1_1_perm16_00_01_t_int_type_00_01std_1238ac09119ee152a24e6f98356538cb5.html': [9,
                                                                                                                                           5,
                                                                                                                                           8],
 'structlibsemigroups_1_1_image_right_action_3_01_h_p_combi_1_1_transf16_00_01_h_p_combi_1_1_p_transf16_01_4.html': [9,
                                                                                                                     5,
                                                                                                                     10],
 'structlibsemigroups_1_1_image_right_action_3_01_mat_00_01_bit_set_3_01_n_01_4_01_4.html': [9,
                                                                                             2,
                                                                                             1],
 'structlibsemigroups_1_1_image_right_action_3_01_mat_00_01_container_01_4.html': [9,
                                                                                   2,
                                                                                   2],
 'structlibsemigroups_1_1_increase_degree.html': [9, 0, 4],
 'structlibsemigroups_1_1_increase_degree_3_01_b_mat8_01_4.html': [9, 3, 4],
 'structlibsemigroups_1_1_increase_degree_3_01_h_p_combi_1_1_b_mat8_01_4.html': [9,
                                                                                 5,
                                                                                 11],
 'structlibsemigroups_1_1_increase_degree_3_01_mat_00_01std_1_1enable__if__t_3_01_is_matrix_3_01_mat_01_4_01_4_01_4.html': [9,
                                                                                                                            4,
                                                                                                                            3],
 'structlibsemigroups_1_1_increase_degree_3_01_p_b_r_01_4.html': [9, 6, 3],
 'structlibsemigroups_1_1_integer_one.html': [11, 1, 0, 1, 0],
 'structlibsemigroups_1_1_integer_plus.html': [11, 1, 0, 1, 1],
 'structlibsemigroups_1_1_integer_prod.html': [11, 1, 0, 1, 2],
 'structlibsemigroups_1_1_integer_zero.html': [11, 1, 0, 1, 3],
 'structlibsemigroups_1_1_inverse.html': [9, 0, 5],
 'structlibsemigroups_1_1_inverse_3_01_b_mat8_01_4.html': [9, 3, 5],
 'structlibsemigroups_1_1_inverse_3_01_h_p_combi_1_1_b_mat8_01_4.html': [9,
                                                                         5,
                                                                         12],
 'structlibsemigroups_1_1_inverse_3_01_h_p_combi_1_1_perm16_01_4.html': [9,
                                                                         5,
                                                                         13],
 'structlibsemigroups_1_1_konieczny_traits.html': [32, 1],
 'structlibsemigroups_1_1_lambda.html': [9, 0, 6],
 'structlibsemigroups_1_1_lambda_3_01_b_mat8_00_01_b_mat8_01_4.html': [9, 3, 6],
 'structlibsemigroups_1_1_lambda_3_01_h_p_combi_1_1_b_mat8_00_01_h_p_combi_1_1_b_mat8_01_4.html': [9,
                                                                                                   5,
                                                                                                   14],
 'structlibsemigroups_1_1_lambda_3_01_h_p_combi_1_1_p_perm16_00_01_h_p_combi_1_1_p_perm16_01_4.html': [9,
                                                                                                       5,
                                                                                                       15],
 'structlibsemigroups_1_1_lambda_3_01_h_p_combi_1_1_transf16_00_01_h_p_combi_1_1_p_transf16_01_4.html': [9,
                                                                                                         5,
                                                                                                         16],
 'structlibsemigroups_1_1_lambda_3_01_mat_00_01_container_01_4.html': [9, 2, 3],
 'structlibsemigroups_1_1_lambda_value.html': [9, 0, 7]};

