/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
const None = null;
var NAVTREE = 
[['libsemigroups',
  'index.html#autotoc_md9',
  [['What is libsemigroups?', 'index.html#autotoc_md10', None],
   ['How to use it', 'index.html#autotoc_md11', None],
   ['Issues', 'index.html#autotoc_md12', None],
   ['Author', 'index.html#autotoc_md13', None],
   ['Contributors', 'index.html#autotoc_md14', None],
   ['Installation', 'index.html#autotoc_md15', None],
   ['Acknowledgements', 'index.html#autotoc_md16', None]]],
 ['Installation and Changelog', '_HEADING_', None],
 ['Install', 'md_install.html', None],
 ['Data structures', '_HEADING_', None],
 ['Adapters',
  'group__adapters__group.html',
  [['No default implementation',
    None,
    [['Complexity', 'structlibsemigroups_1_1_complexity.html', None],
     ['Degree', 'structlibsemigroups_1_1_degree.html', None],
     ['ImageLeftAction',
      'structlibsemigroups_1_1_image_left_action.html',
      None],
     ['ImageRightAction',
      'structlibsemigroups_1_1_image_right_action.html',
      None],
     ['IncreaseDegree', 'structlibsemigroups_1_1_increase_degree.html', None],
     ['Inverse', 'structlibsemigroups_1_1_inverse.html', None],
     ['Lambda', 'structlibsemigroups_1_1_lambda.html', None],
     ['LambdaValue', 'structlibsemigroups_1_1_lambda_value.html', None],
     ['One', 'structlibsemigroups_1_1_one.html', None],
     ['Product', 'structlibsemigroups_1_1_product.html', None],
     ['Rho', 'structlibsemigroups_1_1_rho.html', None],
     ['RhoValue', 'structlibsemigroups_1_1_rho_value.html', None]]],
   ['Default implementation',
    None,
    [['EqualTo', 'structlibsemigroups_1_1_equal_to.html', None],
     ['Hash', 'structlibsemigroups_1_1_hash.html', None],
     ['Less', 'structlibsemigroups_1_1_less.html', None],
     ['OnTuples', 'structlibsemigroups_1_1_on_tuples.html', None],
     ['OnSets', 'structlibsemigroups_1_1_on_sets.html', None],
     ['RankState', 'classlibsemigroups_1_1_rank_state.html', None],
     ['Swap', 'structlibsemigroups_1_1_swap.html', None]]],
   ['Adapters for BMat', 'group__adapters__bmat__group.html', None],
   ['Adapters for BMat8', 'group__adapters__bmat8__group.html', None],
   ['Adapters for other matrices', 'group__adapters__matrix__group.html', None],
   ['Adapters for HPCombi', 'group__adapters__hpcombi__group.html', None],
   ['Adapters for PBR', 'group__adapters__pbr__group.html', None]]],
 ['Elements',
  'group__elements__group.html',
  [['Bipartitions',
    'group__bipart__group.html',
    [['The Bipartition class', 'classlibsemigroups_1_1_bipartition.html', None],
     ['The Blocks class', 'classlibsemigroups_1_1_blocks.html', None],
     ['Bipartition helper functions',
      'namespacelibsemigroups_1_1bipartition.html',
      None],
     ['Blocks helper functions', 'namespacelibsemigroups_1_1blocks.html', None],
     ['make<Biparition>', 'group__make__bipart__group.html', None],
     ['make<Blocks>', 'group__make__blocks__group.html', None]]],
   ['Matrices',
    'group__matrix__group.html',
    [['Over specific semirings',
      None,
      [['Boolean matrices', 'group__bmat__index__group.html', None],
       ['Integer matrices', 'group__intmat__group.html', None],
       ['Max-plus matrices', 'group__maxplusmat__group.html', None],
       ['Min-plus matrices', 'group__minplusmat__group.html', None],
       ['Truncated max-plus matrices',
        'group__maxplustruncmat__group.html',
        None],
       ['Truncated min-plus matrices',
        'group__minplustruncmat__group.html',
        None],
       ['Matrices over ℕ/(t = t + p)', 'group__ntpmat__group.html', None],
       ['Projective max-plus matrices',
        'group__projmaxplus__group.html',
        None]]],
     ['Over arbitrary semirings',
      None,
      [['DynamicMatrix (compile-time)',
        'classlibsemigroups_1_1_dynamic_matrix_3_01_plus_op_00_01_prod_op_00_01_zero_op_00_01_one_op_00_01_scalar_01_4.html#DynamicMatrixStaticArith',
        None],
       ['DynamicMatrix (run-time)',
        'classlibsemigroups_1_1_dynamic_matrix_3_01_semiring_00_01_scalar_01_4.html#DynamicMatrixDynamicArith',
        None],
       ['StaticMatrix', 'classlibsemigroups_1_1_static_matrix.html', None]]],
     ['Row views',
      None,
      [['DynamicRowView (compile-time)',
        'classlibsemigroups_1_1_dynamic_row_view_3_01_plus_op_00_01_prod_op_00_01_zero_op_00_01_one_op_00_01_scalar_01_4.html#DynamicRowViewStaticArith',
        None],
       ['DynamicRowView (run-time)',
        'classlibsemigroups_1_1_dynamic_row_view_3_01_semiring_00_01_scalar_01_4.html#DynamicRowViewDynamicArith',
        None],
       ['StaticRowView', 'classlibsemigroups_1_1_static_row_view.html', None]]],
     ['make<Matrix>', 'group__make__matrix__group.html', None]]],
   ['Partitioned binary relations (PBRs)',
    'group__pbr__group.html',
    [['PBR', 'classlibsemigroups_1_1_p_b_r.html', None],
     ['PBR helper functions', 'namespacelibsemigroups_1_1pbr.html', None],
     ['make<PBR>', 'group__make__pbr__group.html', None]]],
   ['Transformations', 'group__transf__group.html', None]]],
 ['Miscellaneous',
  'group__misc__group.html',
  [['Constants', 'group__constants__group.html', None],
   ['IsObviouslyInfinite', 'group__obvinf__group.html', None],
   ['LibsemigroupsException', 'group__exception__group.html', None],
   ['Reporter', 'classlibsemigroups_1_1_reporter.html', None],
   ['Runner', 'classlibsemigroups_1_1_runner.html', None],
   ['Types', 'group__types__group.html', None]]],
 ['Orders', 'group__orders__group.html', None],
 ['Presentations',
  'group__presentations__group.html',
  [['The Presentation class', 'classlibsemigroups_1_1_presentation.html', None],
   ['The InversePresentation class',
    'classlibsemigroups_1_1_inverse_presentation.html',
    None],
   ['Helper functions', 'namespacelibsemigroups_1_1presentation.html', None],
   ['Examples',
    'namespacelibsemigroups_1_1presentation_1_1examples.html',
    None],
   ['to<Presentation>', 'group__to__presentation__group.html', None],
   ['to<InversePresentation>',
    'group__to__inverse__presentation__group.html',
    None]]],
 ['Ranges', 'group__ranges__group.html', None],
 ['Suffix trees', 'group__ukkonen__group.html', None],
 ['Tries', 'group__aho__corasick__group.html', None],
 ['The `make` function', 'group__make__group.html', None],
 ['The `to` function', 'group__to__group.html', None],
 ['Visualisation', 'group__dot__group.html', None],
 ['Word graphs',
  'group__word__graph__group.html',
  [['Forest', 'classlibsemigroups_1_1_forest.html', None],
   ['make<Forest>', 'group__make__forest__group.html', None],
   ['Gabow', 'group__gabow__group.html', None],
   ['Joiner', 'classlibsemigroups_1_1_joiner.html', None],
   ['Meeter', 'classlibsemigroups_1_1_meeter.html', None],
   ['Paths', 'group__paths__group.html', None],
   ['WordGraph', 'classlibsemigroups_1_1_word_graph.html', None],
   ['WordGraph helper functions',
    'namespacelibsemigroups_1_1word__graph.html',
    None],
   ['make<WordGraph>', 'group__make__word__graph__group.html', None]]],
 ['Words',
  'group__words__group.html',
  [['WordRange', 'classlibsemigroups_1_1_word_range.html', None],
   ['StringRange', 'classlibsemigroups_1_1_string_range.html', None],
   ['ToWord', 'classlibsemigroups_1_1_to_word.html', None],
   ['ToString', 'classlibsemigroups_1_1_to_string.html', None],
   ['Functions for words and strings',
    'namespacelibsemigroups_1_1words.html',
    None],
   ['Literals', 'namespacelibsemigroups_1_1literals.html', None]]],
 ['Main Algorithms', '_HEADING_', None],
 ['Actions',
  'group__action__group.html',
  [['side',
    'group__action__group.html#gafc015eff6557e84151d2e53b94375445',
    None],
   ['Action', 'classlibsemigroups_1_1_action.html', None],
   ['RightAction',
    'group__action__group.html#ga1288ede08d1b9494336b874ad4da177e',
    None]]],
 ['Common congruence helper function',
  'group__cong__common__helpers__group.html',
  [['Add generating pairs',
    'group__cong__common__helpers__add__pair__group.html',
    None],
   ['Containment', 'group__cong__common__helpers__contains__group.html', None],
   ['Reduce a word', 'group__cong__common__helpers__reduce__group.html', None],
   ['Partitioning',
    'group__cong__common__helpers__partition__group.html',
    None]]],
 ['Congruence',
  'group__congruence__group.html',
  [['The Congruence class',
    'group__congruence__class__group.html',
    [['Member types', 'group__congruence__class__mem__types__group.html', None],
     ['Constructors + Initializers',
      'group__congruence__class__init__group.html',
      None],
     ['Settings', 'group__congruence__class__settings__group.html', None],
     ['Common member functions',
      'group__congruence__class__intf__group.html',
      None],
     ['Accessors', 'group__congruence__class__accessors__group.html', None]]],
   ['Congruence helper functions',
    'group__congruence__helpers__group.html',
    None],
   ['to<Congruence>', 'group__to__cong__group.html', None]]],
 ['Froidure-Pin',
  'group__froidure__pin__group.html',
  [['The FroidurePin class', 'classlibsemigroups_1_1_froidure_pin.html', None],
   ['The FroidurePinBase class',
    'classlibsemigroups_1_1_froidure_pin_base.html',
    None],
   ['The FroidurePinTraits class',
    'structlibsemigroups_1_1_froidure_pin_traits.html',
    None],
   ['FroidurePin helper functions',
    'namespacelibsemigroups_1_1froidure__pin.html',
    None],
   ['to<FroidurePin>', 'group__to__froidure__pin__group.html', None],
   ['make<FroidurePin>', 'group__make__froidure__pin__group.html', None]]],
 ['Kambites',
  'group__kambites__group.html',
  [['The Kambites class',
    'group__kambites__class__group.html',
    [['Member types', 'group__kambites__class__mem__types__group.html', None],
     ['Constructors + Initializers',
      'group__kambites__class__init__group.html',
      None],
     ['Common member functions',
      'group__kambites__class__intf__group.html',
      None],
     ['Accessors', 'group__kambites__class__accessors__group.html', None]]],
   ['Kambites helper functions',
    'group__kambites__helpers__group.html',
    None]]],
 ['Knuth-Bendix',
  'group__knuth__bendix__group.html',
  [['The KnuthBendix class',
    'group__knuth__bendix__class__group.html',
    [['Member types',
      'group__knuth__bendix__class__mem__types__group.html',
      None],
     ['Constructors + Initializers',
      'group__knuth__bendix__class__init__group.html',
      None],
     ['Settings', 'group__knuth__bendix__class__settings__group.html', None],
     ['Common member functions',
      'group__knuth__bendix__class__intf__group.html',
      None],
     ['Accessors',
      'group__knuth__bendix__class__accessors__group.html',
      None]]],
   ['Knuth-Bendix helper functions',
    'group__knuth__bendix__helpers__group.html',
    None],
   ['to<KnuthBendix>', 'group__to__knuth__bendix__group.html', None]]],
 ['Radoszewski-Rytter', 'group__freeband__group.html', None],
 ['Schreier-Sims', 'group__schreier__sims__group.html', None],
 ['Low Index Congruences',
  'group__sims__group.html',
  [['Classes',
    'group__sims__group.html#nested-classes',
    [['MinimalRepOrc', 'classlibsemigroups_1_1_minimal_rep_orc.html', None],
     ['RepOrc', 'classlibsemigroups_1_1_rep_orc.html', None],
     ['Sims1', 'classlibsemigroups_1_1_sims1.html', None],
     ['Sims2', 'classlibsemigroups_1_1_sims2.html', None],
     ['SimsRefinerIdeals',
      'classlibsemigroups_1_1_sims_refiner_ideals.html',
      None],
     ['SimsSettings', 'classlibsemigroups_1_1_sims_settings.html', None],
     ['SimsStats', 'classlibsemigroups_1_1_sims_stats.html', None],
     ['SimsRefinerFaithful',
      'classlibsemigroups_1_1_sims_refiner_faithful.html',
      None]]],
   ['Helper functions', 'namespacelibsemigroups_1_1sims.html', None]]],
 ['Stephen',
  'group__stephen__group.html',
  [['The Stephen class', 'classlibsemigroups_1_1_stephen.html', None],
   ['Stephen helper functions',
    'namespacelibsemigroups_1_1stephen.html',
    None]]],
 ['Todd-Coxeter',
  'group__todd__coxeter__group.html',
  [['The ToddCoxeter class',
    'group__todd__coxeter__class__group.html',
    [['Member types',
      'group__todd__coxeter__class__mem__types__group.html',
      [['The options nested struct',
        'structlibsemigroups_1_1_todd_coxeter_1_1options.html',
        None]]],
     ['Constructors + Initializers',
      'group__todd__coxeter__class__init__group.html',
      None],
     ['Settings', 'group__todd__coxeter__class__settings__group.html', None],
     ['Common functions',
      'group__todd__coxeter__class__intf__group.html',
      None],
     ['Accessors', 'group__todd__coxeter__class__accessors__group.html', None],
     ['Modifiers', 'group__todd__coxeter__class__mod__group.html', None],
     ['Word -> index',
      'group__todd__coxeter__class__word__index__group.html',
      None],
     ['Index -> word',
      'group__todd__coxeter__class__index__word__group.html',
      None]]],
   ['Todd-Coxeter helper functions',
    'group__todd__coxeter__helpers__group.html',
    None],
   ['to<ToddCoxeter>', 'group__to__todd__coxeter__group.html', None]]],
 ['Bibliography', '_HEADING_', None],
 ['Bibliography', 'citelist.html', None],
 ['Further info', '_HEADING_', None],
 ['GitHub', '^https://github.com/libsemigroups/libsemigroups', None]];


var NAVTREEINDEX =
[
"_HEADING_"
];

var SYNCONMSG = 'click to disable panel synchronization';
var SYNCOFFMSG = 'click to enable panel synchronization';