var searchData=
[
  ['matrixoversemiring',['MatrixOverSemiring',['../classlibsemigroups_1_1_matrix_over_semiring.html',1,'libsemigroups']]],
  ['matrixoversemiringbase',['MatrixOverSemiringBase',['../classlibsemigroups_1_1_matrix_over_semiring_base.html',1,'libsemigroups::MatrixOverSemiringBase&lt; TValueType, TSubclass &gt;'],['../classlibsemigroups_1_1_matrix_over_semiring_base.html#a99fee19c8ce933e2473afc16924f2f3f',1,'libsemigroups::MatrixOverSemiringBase::MatrixOverSemiringBase(std::vector&lt; TValueType &gt; *matrix, Semiring&lt; TValueType &gt; const *semiring)'],['../classlibsemigroups_1_1_matrix_over_semiring_base.html#a0ea7d30dcc61d160462835cffed2a2aa',1,'libsemigroups::MatrixOverSemiringBase::MatrixOverSemiringBase(std::vector&lt; std::vector&lt; TValueType &gt;&gt; const &amp;matrix, Semiring&lt; TValueType &gt; const *semiring)'],['../classlibsemigroups_1_1_matrix_over_semiring_base.html#af72c7f10db4c290c5d21e0b3697a6eae',1,'libsemigroups::MatrixOverSemiringBase::MatrixOverSemiringBase(std::vector&lt; TValueType &gt; *matrix)']]],
  ['matrixoversemiringbase_3c_20bool_2c_20booleanmat_20_3e',['MatrixOverSemiringBase&lt; bool, BooleanMat &gt;',['../classlibsemigroups_1_1_matrix_over_semiring_base.html',1,'libsemigroups']]],
  ['matrixoversemiringbase_3c_20int64_5ft_2c_20projectivemaxplusmatrix_20_3e',['MatrixOverSemiringBase&lt; int64_t, ProjectiveMaxPlusMatrix &gt;',['../classlibsemigroups_1_1_matrix_over_semiring_base.html',1,'libsemigroups']]],
  ['matrixoversemiringbase_3c_20tvaluetype_2c_20matrixoversemiring_3c_20tvaluetype_20_3e_20_3e',['MatrixOverSemiringBase&lt; TValueType, MatrixOverSemiring&lt; TValueType &gt; &gt;',['../classlibsemigroups_1_1_matrix_over_semiring_base.html',1,'libsemigroups']]],
  ['maxplussemiring',['MaxPlusSemiring',['../classlibsemigroups_1_1_max_plus_semiring.html',1,'libsemigroups']]],
  ['minimal_5ffactorisation',['minimal_factorisation',['../classlibsemigroups_1_1_semigroup.html#a778113085c6881f60f24856e1f8a9d9f',1,'libsemigroups::Semigroup::minimal_factorisation(word_t &amp;word, element_index_t pos)'],['../classlibsemigroups_1_1_semigroup.html#a57243f01c2ae3ec00382b7fa01eac493',1,'libsemigroups::Semigroup::minimal_factorisation(element_index_t pos)'],['../classlibsemigroups_1_1_semigroup.html#a2de1f5c4422b5c1bd416123a40777f7d',1,'libsemigroups::Semigroup::minimal_factorisation(Element const *x)']]],
  ['minplussemiring',['MinPlusSemiring',['../classlibsemigroups_1_1_min_plus_semiring.html',1,'libsemigroups']]],
  ['minus_5finfty',['MINUS_INFTY',['../classlibsemigroups_1_1_semiring.html#a7e5c5791a1719a2d13160f17caff4249',1,'libsemigroups::Semiring']]]
];
