var searchData=
[
  ['v_0',['v',['../structlibsemigroups_1_1_ukkonen_1_1_state.html#a3f70ff05b02021c295aaaac4610278aa',1,'libsemigroups::Ukkonen::State']]],
  ['va_5flist_1',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray_2',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['valid_3',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['../classlibsemigroups_1_1_word_range.html#a99f77f09f364b20c3a30ab6bffa4c24b',1,'libsemigroups::WordRange::valid()']]],
  ['validate_4',['validate',['../classlibsemigroups_1_1_presentation.html#ab3a68a01a1c7c22bfbd9f3f6d20e7d5a',1,'libsemigroups::Presentation::validate()'],['../classlibsemigroups_1_1_inverse_presentation.html#ab3a68a01a1c7c22bfbd9f3f6d20e7d5a',1,'libsemigroups::InversePresentation::validate()'],['../namespacelibsemigroups_1_1blocks.html#a757e995c21568feb875f500cc3dbd16e',1,'libsemigroups::blocks::validate()'],['../namespacelibsemigroups_1_1bipartition.html#a04fb3bdd5b176e7f868b17f550ca1139',1,'libsemigroups::bipartition::validate()'],['../group__transf__group.html#gaec19a0378e74f34554609c932f1ea3a9',1,'libsemigroups::validate(T const &amp;f) -&gt; std::enable_if_t&lt; IsPTransf&lt; T &gt; &gt;'],['../group__transf__group.html#ga165dadbfb7f1c29dea22ae37617976cd',1,'libsemigroups::validate(Transf&lt; N, Scalar &gt; const &amp;f)'],['../group__transf__group.html#gac71f287f6e14090323eeb7962697331d',1,'libsemigroups::validate(PPerm&lt; N, Scalar &gt; const &amp;f)'],['../group__transf__group.html#gae7fccde0007cc3f499ec3d31335ece43',1,'libsemigroups::validate(Perm&lt; N, Scalar &gt; const &amp;f)']]],
  ['validate_5factive_5fnode_5findex_5',['validate_active_node_index',['../classlibsemigroups_1_1_aho_corasick.html#ab0c024b0b267a446740fee6ec494dcef',1,'libsemigroups::AhoCorasick']]],
  ['validate_5falphabet_6',['validate_alphabet',['../classlibsemigroups_1_1_presentation.html#a85885d8a4c1acbb575dad4aa0a8d9d59',1,'libsemigroups::Presentation']]],
  ['validate_5fletter_7',['validate_letter',['../classlibsemigroups_1_1_presentation.html#a3bb4217863b66992b475a981b801bab5',1,'libsemigroups::Presentation']]],
  ['validate_5fnode_5findex_8',['validate_node_index',['../classlibsemigroups_1_1_aho_corasick.html#a0587a21a4c12958c310fea28c748f990',1,'libsemigroups::AhoCorasick']]],
  ['validate_5frules_9',['validate_rules',['../classlibsemigroups_1_1_presentation.html#aaebf90ae878d5d3b6142c8dc34c231c9',1,'libsemigroups::Presentation::validate_rules()'],['../namespacelibsemigroups_1_1presentation.html#ae5b4b6eb283afeb6c9d546c7c5988bd4',1,'libsemigroups::presentation::validate_rules(Presentation&lt; Word &gt; const &amp;p, Iterator first, Iterator last)']]],
  ['validate_5fsemigroup_5finverses_10',['validate_semigroup_inverses',['../namespacelibsemigroups_1_1presentation.html#a756f5721e810bac90aca39df8f87c080',1,'libsemigroups::presentation']]],
  ['validate_5fword_11',['validate_word',['../classlibsemigroups_1_1_presentation.html#a16828821733416651369b4c1a1628b61',1,'libsemigroups::Presentation']]],
  ['value_12',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()']]],
  ['value_5fcomp_13',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()']]],
  ['value_5fcompare_14',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'multimap::value_compare']]],
  ['value_5for_15',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['value_5ftype_16',['value_type',['../classlibsemigroups_1_1_froidure_pin.html#ab523280552089290cb8b2ba7dea98e9f',1,'libsemigroups::FroidurePin::value_type'],['../classlibsemigroups_1_1detail_1_1_sims_base_1_1iterator.html#a1f9de6eb31616080de6755308243800e',1,'libsemigroups::detail::SimsBase::iterator::value_type'],['../classlibsemigroups_1_1sims_1_1const__rcgp__iterator.html#a2b21c963df58ebb054efa3a10505469a',1,'libsemigroups::sims::const_rcgp_iterator::value_type'],['../classlibsemigroups_1_1sims_1_1const__cgp__iterator.html#a2b21c963df58ebb054efa3a10505469a',1,'libsemigroups::sims::const_cgp_iterator::value_type']]],
  ['vector_17',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'vector'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()']]],
  ['vector_3c_20bool_20_3e_18',['vector&lt; bool &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20bool_2c_20std_3a_3aallocator_3c_20bool_20_3e_20_3e_19',['vector&lt; bool, std::allocator&lt; bool &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20element_5findex_5ftype_20_3e_20',['vector&lt; element_index_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20element_5ftype_20_3e_21',['vector&lt; element_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20enumerate_5findex_5ftype_20_3e_22',['vector&lt; enumerate_index_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20generator_5findex_5ftype_20_3e_23',['vector&lt; generator_index_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20index_5ftype_20_3e_24',['vector&lt; index_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20int_20_3e_25',['vector&lt; int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20internal_5felement_5ftype_20_3e_26',['vector&lt; internal_element_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20internal_5fpoint_5ftype_20_3e_27',['vector&lt; internal_point_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20knuthbendix_5f_20_3e_28',['vector&lt; KnuthBendix_ &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20lambda_5forb_5findex_5ftype_20_3e_29',['vector&lt; lambda_orb_index_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20letter_5ftype_20_3e_30',['vector&lt; letter_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20libsemigroups_3a_3adot_20_3e_31',['vector&lt; libsemigroups::Dot &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20libsemigroups_3a_3adot_3a_3aedge_20_3e_32',['vector&lt; libsemigroups::Dot::Edge &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20libsemigroups_3a_3akonieczny_3a_3adclass_20_2a_20_3e_33',['vector&lt; libsemigroups::Konieczny::DClass * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20libsemigroups_3a_3aukkonen_3a_3anode_20_3e_34',['vector&lt; libsemigroups::Ukkonen::Node &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20native_5fword_5ftype_20_3e_35',['vector&lt; native_word_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20node_20_3e_36',['vector&lt; Node &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20node_2c_20std_3a_3aallocator_3c_20node_20_3e_20_3e_37',['vector&lt; Node, std::allocator&lt; Node &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20node_5ftype_20_3e_38',['vector&lt; node_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20node_5ftype_2c_20std_3a_3aallocator_3c_20node_5ftype_20_3e_20_3e_39',['vector&lt; node_type, std::allocator&lt; node_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20pendingdef_20_3e_40',['vector&lt; PendingDef &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20point_5ftype_20_3e_41',['vector&lt; point_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20regulardclass_20_2a_20_3e_42',['vector&lt; RegularDClass * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20relationwords_20_3e_43',['vector&lt; RelationWords &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20repinfo_20_3e_44',['vector&lt; RepInfo &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20rho_5forb_5findex_5ftype_20_3e_45',['vector&lt; rho_orb_index_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20runnerkind_20_3e_46',['vector&lt; RunnerKind &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20scalar_20_3e_47',['vector&lt; Scalar &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20size_5ft_20_3e_48',['vector&lt; size_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20size_5ftype_20_3e_49',['vector&lt; size_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20state_5ftype_20_3e_50',['vector&lt; state_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20state_5ftype_2c_20std_3a_3aallocator_3c_20state_5ftype_20_3e_20_3e_51',['vector&lt; state_type, std::allocator&lt; state_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aarray_3c_20std_3a_3astring_2c_20c_2b1_20_3e_20_3e_52',['vector&lt; std::array&lt; std::string, C+1 &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3afunction_3c_20bool_28libsemigroups_3a_3awordgraph_3c_20uint32_5ft_20_3e_20const_20_26_29_3e_20_3e_53',['vector&lt; std::function&lt; bool(libsemigroups::WordGraph&lt; uint32_t &gt; const &amp;)&gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20generator_5findex_5ftype_2c_20generator_5findex_5ftype_20_3e_20_3e_54',['vector&lt; std::pair&lt; generator_index_type, generator_index_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20internal_5felement_5ftype_2c_20element_5findex_5ftype_20_3e_20_3e_55',['vector&lt; std::pair&lt; internal_element_type, element_index_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20node_5ftype_2c_20label_5ftype_20_3e_20_3e_56',['vector&lt; std::pair&lt; node_type, label_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20uint64_5ft_2c_20uint64_5ft_20_3e_20_3e_57',['vector&lt; std::pair&lt; uint64_t, uint64_t &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20libsemigroups_3a_3arunner_20_3e_20_3e_58',['vector&lt; std::shared_ptr&lt; libsemigroups::Runner &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e_59',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3athread_20_3e_60',['vector&lt; std::thread &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20settings_20_3e_20_3e_61',['vector&lt; std::unique_ptr&lt; Settings &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20d_5fclass_5findex_5ftype_20_3e_20_3e_62',['vector&lt; std::vector&lt; D_class_index_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20index_5ftype_20_3e_20_3e_63',['vector&lt; std::vector&lt; index_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20letter_5ftype_20_3e_20_3e_64',['vector&lt; std::vector&lt; letter_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20node_5ftype_20_3e_20_3e_65',['vector&lt; std::vector&lt; node_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20repinfo_20_3e_20_3e_66',['vector&lt; std::vector&lt; RepInfo &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20t_20_3e_20_3e_20const_20_26_67',['vector&lt; std::vector&lt; T &gt; &gt; const &amp;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20uint32_5ft_20_3e_20_3e_68',['vector&lt; std::vector&lt; uint32_t &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20stringview_20_3e_69',['vector&lt; StringView &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20t_2c_20std_3a_3aallocator_3c_20t_20_3e_20_3e_70',['vector&lt; T, std::allocator&lt; T &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20uint32_5ft_20_3e_71',['vector&lt; uint32_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20uint64_5ft_20_3e_72',['vector&lt; uint64_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20value_5ftype_20_3e_73',['vector&lt; value_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20word_20_3e_74',['vector&lt; Word &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20word_5ftype_20_3e_75',['vector&lt; word_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_5ftype_76',['vector_type',['../classlibsemigroups_1_1_p_b_r.html#a9cf00f4ce8829a0b02aa81e98bbc6194',1,'libsemigroups::PBR']]],
  ['vfprintf_77',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_78',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_79',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_80',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['views_81',['Row views',['../group__matrix__group.html#autotoc_md6',1,'']]],
  ['visualisation_82',['Visualisation',['../group__dot__group.html',1,'']]],
  ['vprintf_83',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_84',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_85',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_86',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_87',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_88',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_89',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_90',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_91',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
