var searchData=
[
  ['u16streampos_0',['u16streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u16string_1',['u16string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['u32streampos_2',['u32streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u32string_3',['u32string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['uint16_5ft_4',['uint16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint32_5ft_5',['uint32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint64_5ft_6',['uint64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint8_5ft_7',['uint8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast16_5ft_8',['uint_fast16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast32_5ft_9',['uint_fast32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast64_5ft_10',['uint_fast64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast8_5ft_11',['uint_fast8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast16_5ft_12',['uint_least16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast32_5ft_13',['uint_least32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast64_5ft_14',['uint_least64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast8_5ft_15',['uint_least8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintmax_5ft_16',['uintmax_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintptr_5ft_17',['uintptr_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['ukkonen_18',['Ukkonen',['../classlibsemigroups_1_1_ukkonen.html',1,'libsemigroups']]],
  ['unary_5ffunction_19',['unary_function',['http://en.cppreference.com/w/cpp/utility/functional/unary_function.html',1,'std']]],
  ['unary_5fnegate_20',['unary_negate',['http://en.cppreference.com/w/cpp/utility/functional/unary_negate.html',1,'std']]],
  ['underflow_5ferror_21',['underflow_error',['http://en.cppreference.com/w/cpp/error/underflow_error.html',1,'std']]],
  ['underlying_5ftype_22',['underlying_type',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['unexpected_5fhandler_23',['unexpected_handler',['http://en.cppreference.com/w/cpp/error/unexpected_handler.html',1,'std']]],
  ['uniform_5fint_5fdistribution_24',['uniform_int_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution.html',1,'std']]],
  ['uniform_5freal_5fdistribution_25',['uniform_real_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution.html',1,'std']]],
  ['unique_5flock_26',['unique_lock',['http://en.cppreference.com/w/cpp/thread/unique_lock.html',1,'std']]],
  ['unique_5fptr_27',['unique_ptr',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20overlapmeasure_20_3e_28',['unique_ptr&lt; OverlapMeasure &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20rulecontainer_20_3e_29',['unique_ptr&lt; RuleContainer &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unordered_5fmap_30',['unordered_map',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20index_5ftype_2c_20rule_20_2a_20_3e_31',['unordered_map&lt; index_type, Rule * &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20internal_5fconst_5felement_5ftype_2c_20element_5findex_5ftype_2c_20internalhash_2c_20internalequalto_20_3e_32',['unordered_map&lt; internal_const_element_type, element_index_type, InternalHash, InternalEqualTo &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20internal_5fconst_5fpoint_5ftype_2c_20size_5ft_2c_20internalhash_2c_20internalequalto_20_3e_33',['unordered_map&lt; internal_const_point_type, size_t, InternalHash, InternalEqualTo &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20lambda_5forb_5findex_5ftype_2c_20std_3a_3avector_3c_20d_5fclass_5findex_5ftype_20_3e_20_3e_34',['unordered_map&lt; lambda_orb_index_type, std::vector&lt; D_class_index_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20letter_5ftype_2c_20char_20_3e_35',['unordered_map&lt; letter_type, char &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20letter_5ftype_2c_20index_5ftype_20_3e_36',['unordered_map&lt; letter_type, index_type &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20letter_5ftype_2c_20size_5ftype_20_3e_37',['unordered_map&lt; letter_type, size_type &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20rho_5forb_5findex_5ftype_2c_20std_3a_3avector_3c_20d_5fclass_5findex_5ftype_20_3e_20_3e_38',['unordered_map&lt; rho_orb_index_type, std::vector&lt; D_class_index_type &gt; &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20std_3a_3apair_3c_20rho_5forb_5findex_5ftype_2c_20lambda_5forb_5findex_5ftype_20_3e_2c_20lambda_5forb_5findex_5ftype_2c_20pairhash_20_3e_39',['unordered_map&lt; std::pair&lt; rho_orb_index_type, lambda_orb_index_type &gt;, lambda_orb_index_type, PairHash &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20std_3a_3apair_3c_20rho_5forb_5findex_5ftype_2c_20lambda_5forb_5findex_5ftype_20_3e_2c_20rho_5forb_5findex_5ftype_2c_20pairhash_20_3e_40',['unordered_map&lt; std::pair&lt; rho_orb_index_type, lambda_orb_index_type &gt;, rho_orb_index_type, PairHash &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20std_3a_3apair_3c_20uint64_5ft_2c_20uint64_5ft_20_3e_2c_20uint64_5ft_2c_20libsemigroups_3a_3ahash_3c_20std_3a_3apair_3c_20uint64_5ft_2c_20uint64_5ft_20_3e_20_3e_20_3e_41',['unordered_map&lt; std::pair&lt; uint64_t, uint64_t &gt;, uint64_t, libsemigroups::Hash&lt; std::pair&lt; uint64_t, uint64_t &gt; &gt; &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20std_3a_3athread_3a_3aid_2c_20knuthbendix_5f_20_3e_42',['unordered_map&lt; std::thread::id, KnuthBendix_ &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20typename_20from_3a_3avalue_5ftype_2c_20letter_5ftype_20_3e_43',['unordered_map&lt; typename From::value_type, letter_type &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20typename_20std_3a_3astring_3a_3avalue_5ftype_2c_20letter_5ftype_20_3e_44',['unordered_map&lt; typename std::string::value_type, letter_type &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmultimap_45',['unordered_multimap',['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std']]],
  ['unordered_5fmultiset_46',['unordered_multiset',['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std']]],
  ['unordered_5fset_47',['unordered_set',['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std']]],
  ['unordered_5fset_3c_20index_5ftype_20_3e_48',['unordered_set&lt; index_type &gt;',['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std']]],
  ['uses_5fallocator_49',['uses_allocator',['http://en.cppreference.com/w/cpp/memory/uses_allocator.html',1,'std']]]
];
