var searchData=
[
  ['schreiersims_0',['SchreierSims',['../classlibsemigroups_1_1_schreier_sims.html',1,'libsemigroups']]],
  ['schreiersimstraits_1',['SchreierSimsTraits',['../structlibsemigroups_1_1_schreier_sims_traits.html',1,'libsemigroups']]],
  ['scoped_5fallocator_5fadaptor_2',['scoped_allocator_adaptor',['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor.html',1,'std']]],
  ['seconds_3',['seconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['seed_5fseq_4',['seed_seq',['http://en.cppreference.com/w/cpp/numeric/random/seed_seq.html',1,'std']]],
  ['sentry_5',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'basic_ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'basic_istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'basic_istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'istrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'ostrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'strstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wfstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'wifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wiostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'wistream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'wistringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wstringstream::sentry']]],
  ['set_6',['set',['http://en.cppreference.com/w/cpp/container/set.html',1,'std']]],
  ['set_3c_20index_5ftype_20_3e_7',['set&lt; index_type &gt;',['http://en.cppreference.com/w/cpp/container/set.html',1,'std']]],
  ['set_3c_20rank_5ftype_20_3e_8',['set&lt; rank_type &gt;',['http://en.cppreference.com/w/cpp/container/set.html',1,'std']]],
  ['set_3c_20rulelookup_20_3e_9',['set&lt; RuleLookup &gt;',['http://en.cppreference.com/w/cpp/container/set.html',1,'std']]],
  ['shared_5ffuture_10',['shared_future',['http://en.cppreference.com/w/cpp/thread/shared_future.html',1,'std']]],
  ['shared_5flock_11',['shared_lock',['http://en.cppreference.com/w/cpp/thread/shared_lock.html',1,'std']]],
  ['shared_5fptr_12',['shared_ptr',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20libsemigroups_3a_3arunner_20_3e_13',['shared_ptr&lt; libsemigroups::Runner &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20presentationtype_20_3e_14',['shared_ptr&lt; PresentationType &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20state_5ftype_20_3e_15',['shared_ptr&lt; state_type &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5ftimed_5fmutex_16',['shared_timed_mutex',['http://en.cppreference.com/w/cpp/thread/shared_timed_mutex.html',1,'std']]],
  ['shortlexcompare_17',['ShortLexCompare',['../structlibsemigroups_1_1_short_lex_compare.html',1,'libsemigroups']]],
  ['shuffle_5forder_5fengine_18',['shuffle_order_engine',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine.html',1,'std']]],
  ['sig_5fatomic_5ft_19',['sig_atomic_t',['http://en.cppreference.com/w/cpp/utility/program/sig_atomic_t.html',1,'std']]],
  ['sims1_20',['Sims1',['../classlibsemigroups_1_1_sims1.html',1,'libsemigroups']]],
  ['sims2_21',['Sims2',['../classlibsemigroups_1_1_sims2.html',1,'libsemigroups']]],
  ['simsrefinerfaithful_22',['SimsRefinerFaithful',['../classlibsemigroups_1_1_sims_refiner_faithful.html',1,'libsemigroups']]],
  ['simsrefinerideals_23',['SimsRefinerIdeals',['../classlibsemigroups_1_1_sims_refiner_ideals.html',1,'libsemigroups']]],
  ['simssettings_24',['SimsSettings',['../classlibsemigroups_1_1_sims_settings.html',1,'libsemigroups']]],
  ['simssettings_3c_20minimalreporc_20_3e_25',['SimsSettings&lt; MinimalRepOrc &gt;',['../classlibsemigroups_1_1_sims_settings.html',1,'libsemigroups']]],
  ['simssettings_3c_20reporc_20_3e_26',['SimsSettings&lt; RepOrc &gt;',['../classlibsemigroups_1_1_sims_settings.html',1,'libsemigroups']]],
  ['simssettings_3c_20sims1or2_20_3e_27',['SimsSettings&lt; Sims1or2 &gt;',['../classlibsemigroups_1_1_sims_settings.html',1,'libsemigroups']]],
  ['simsstats_28',['SimsStats',['../classlibsemigroups_1_1_sims_stats.html',1,'libsemigroups']]],
  ['size_5ft_29',['size_t',['http://en.cppreference.com/w/cpp/types/size_t.html',1,'std']]],
  ['smallestinteger_30',['SmallestInteger',['../structlibsemigroups_1_1_smallest_integer.html',1,'libsemigroups']]],
  ['smatch_31',['smatch',['http://en.cppreference.com/w/cpp/regex/match_results.html',1,'std']]],
  ['sregex_5fiterator_32',['sregex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['sregex_5ftoken_5fiterator_33',['sregex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['ssub_5fmatch_34',['ssub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['stack_35',['stack',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['stack_3c_20coincidence_20_3e_36',['stack&lt; Coincidence &gt;',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['stack_3c_20index_5ftype_20_3e_37',['stack&lt; index_type &gt;',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['stack_3c_20std_3a_3apair_3c_20uint64_5ft_2c_20uint64_5ft_20_3e_20_3e_38',['stack&lt; std::pair&lt; uint64_t, uint64_t &gt; &gt;',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['state_39',['State',['../structlibsemigroups_1_1_ukkonen_1_1_state.html',1,'libsemigroups::Ukkonen']]],
  ['state_5ftype_40',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt_byname::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt_utf8::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt_utf8_utf16::state_type']]],
  ['staticmatrix_41',['StaticMatrix',['../classlibsemigroups_1_1_static_matrix.html',1,'libsemigroups']]],
  ['staticmatrix_3c_20booleanplus_2c_20booleanprod_2c_20booleanzero_2c_20booleanone_2c_20r_2c_20c_2c_20int_20_3e_42',['StaticMatrix&lt; BooleanPlus, BooleanProd, BooleanZero, BooleanOne, R, C, int &gt;',['../classlibsemigroups_1_1_static_matrix.html',1,'libsemigroups']]],
  ['staticmatrix_3c_20integerplus_3c_20scalar_20_3e_2c_20integerprod_3c_20scalar_20_3e_2c_20integerzero_3c_20scalar_20_3e_2c_20integerone_3c_20scalar_20_3e_2c_20r_2c_20c_2c_20scalar_20_3e_43',['StaticMatrix&lt; IntegerPlus&lt; Scalar &gt;, IntegerProd&lt; Scalar &gt;, IntegerZero&lt; Scalar &gt;, IntegerOne&lt; Scalar &gt;, R, C, Scalar &gt;',['../classlibsemigroups_1_1_static_matrix.html',1,'libsemigroups']]],
  ['staticmatrix_3c_20maxplusplus_3c_20scalar_20_3e_2c_20maxplusprod_3c_20scalar_20_3e_2c_20maxpluszero_3c_20scalar_20_3e_2c_20integerzero_3c_20scalar_20_3e_2c_20r_2c_20c_2c_20scalar_20_3e_44',['StaticMatrix&lt; MaxPlusPlus&lt; Scalar &gt;, MaxPlusProd&lt; Scalar &gt;, MaxPlusZero&lt; Scalar &gt;, IntegerZero&lt; Scalar &gt;, R, C, Scalar &gt;',['../classlibsemigroups_1_1_static_matrix.html',1,'libsemigroups']]],
  ['staticmatrix_3c_20maxplusplus_3c_20scalar_20_3e_2c_20maxplustruncprod_3c_20t_2c_20scalar_20_3e_2c_20maxpluszero_3c_20scalar_20_3e_2c_20integerzero_3c_20scalar_20_3e_2c_20r_2c_20c_2c_20scalar_20_3e_45',['StaticMatrix&lt; MaxPlusPlus&lt; Scalar &gt;, MaxPlusTruncProd&lt; T, Scalar &gt;, MaxPlusZero&lt; Scalar &gt;, IntegerZero&lt; Scalar &gt;, R, C, Scalar &gt;',['../classlibsemigroups_1_1_static_matrix.html',1,'libsemigroups']]],
  ['staticmatrix_3c_20minplusplus_3c_20scalar_20_3e_2c_20minplusprod_3c_20scalar_20_3e_2c_20minpluszero_3c_20scalar_20_3e_2c_20integerzero_3c_20scalar_20_3e_2c_20r_2c_20c_2c_20scalar_20_3e_46',['StaticMatrix&lt; MinPlusPlus&lt; Scalar &gt;, MinPlusProd&lt; Scalar &gt;, MinPlusZero&lt; Scalar &gt;, IntegerZero&lt; Scalar &gt;, R, C, Scalar &gt;',['../classlibsemigroups_1_1_static_matrix.html',1,'libsemigroups']]],
  ['staticmatrix_3c_20minplusplus_3c_20scalar_20_3e_2c_20minplustruncprod_3c_20t_2c_20scalar_20_3e_2c_20minpluszero_3c_20scalar_20_3e_2c_20integerzero_3c_20scalar_20_3e_2c_20r_2c_20c_2c_20scalar_20_3e_47',['StaticMatrix&lt; MinPlusPlus&lt; Scalar &gt;, MinPlusTruncProd&lt; T, Scalar &gt;, MinPlusZero&lt; Scalar &gt;, IntegerZero&lt; Scalar &gt;, R, C, Scalar &gt;',['../classlibsemigroups_1_1_static_matrix.html',1,'libsemigroups']]],
  ['staticmatrix_3c_20ntpplus_3c_20t_2c_20p_2c_20scalar_20_3e_2c_20ntpprod_3c_20t_2c_20p_2c_20scalar_20_3e_2c_20integerzero_3c_20scalar_20_3e_2c_20integerone_3c_20scalar_20_3e_2c_20r_2c_20c_2c_20scalar_20_3e_48',['StaticMatrix&lt; NTPPlus&lt; T, P, Scalar &gt;, NTPProd&lt; T, P, Scalar &gt;, IntegerZero&lt; Scalar &gt;, IntegerOne&lt; Scalar &gt;, R, C, Scalar &gt;',['../classlibsemigroups_1_1_static_matrix.html',1,'libsemigroups']]],
  ['staticmatrix_3c_20plusop_2c_20prodop_2c_20zeroop_2c_20oneop_2c_201_2c_20c_2c_20scalar_20_3e_49',['StaticMatrix&lt; PlusOp, ProdOp, ZeroOp, OneOp, 1, C, Scalar &gt;',['../classlibsemigroups_1_1_static_matrix.html',1,'libsemigroups']]],
  ['staticptransf_50',['StaticPTransf',['../classlibsemigroups_1_1_static_p_transf.html',1,'libsemigroups']]],
  ['staticrowview_51',['StaticRowView',['../classlibsemigroups_1_1_static_row_view.html',1,'libsemigroups']]],
  ['steady_5fclock_52',['steady_clock',['http://en.cppreference.com/w/cpp/chrono/steady_clock.html',1,'std::chrono']]],
  ['stephen_53',['Stephen',['../classlibsemigroups_1_1_stephen.html',1,'libsemigroups']]],
  ['streambuf_54',['streambuf',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['streamoff_55',['streamoff',['http://en.cppreference.com/w/cpp/io/streamoff.html',1,'std']]],
  ['streampos_56',['streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['streamsize_57',['streamsize',['http://en.cppreference.com/w/cpp/io/streamsize.html',1,'std']]],
  ['string_58',['string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['string_5ftype_59',['string_type',['http://en.cppreference.com/w/cpp/locale/collate.html',1,'collate::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'collate_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'messages::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'messages_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/money_get.html',1,'money_get::string_type'],['http://en.cppreference.com/w/cpp/locale/money_put.html',1,'money_put::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'moneypunct::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'moneypunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'numpunct::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'numpunct_byname::string_type']]],
  ['stringbuf_60',['stringbuf',['http://en.cppreference.com/w/cpp/io/basic_stringbuf.html',1,'std']]],
  ['stringrange_61',['StringRange',['../classlibsemigroups_1_1_string_range.html',1,'libsemigroups']]],
  ['stringstream_62',['stringstream',['http://en.cppreference.com/w/cpp/io/basic_stringstream.html',1,'std']]],
  ['strstream_63',['strstream',['http://en.cppreference.com/w/cpp/io/strstream.html',1,'std']]],
  ['strstreambuf_64',['strstreambuf',['http://en.cppreference.com/w/cpp/io/strstreambuf.html',1,'std']]],
  ['student_5ft_5fdistribution_65',['student_t_distribution',['http://en.cppreference.com/w/cpp/numeric/random/student_t_distribution.html',1,'std']]],
  ['sub_5fmatch_66',['sub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['subtract_5fwith_5fcarry_5fengine_67',['subtract_with_carry_engine',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['swap_68',['Swap',['../structlibsemigroups_1_1_swap.html',1,'libsemigroups']]],
  ['swap_3c_20element_20_3e_69',['Swap&lt; Element &gt;',['../structlibsemigroups_1_1_swap.html',1,'libsemigroups']]],
  ['swap_3c_20element_5ftype_20_3e_70',['Swap&lt; element_type &gt;',['../structlibsemigroups_1_1_swap.html',1,'libsemigroups']]],
  ['swap_3c_20thing_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fbase_5fof_5fv_3c_20hpcombi_3a_3aptransf16_2c_20thing_20_3e_20_3e_20_3e_71',['Swap&lt; Thing, std::enable_if_t&lt; std::is_base_of_v&lt; HPCombi::PTransf16, Thing &gt; &gt; &gt;',['../structlibsemigroups_1_1_swap_3_01_thing_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_005aaca2985d1f9de4a59374f3a4dde82.html',1,'libsemigroups']]],
  ['system_5fclock_72',['system_clock',['http://en.cppreference.com/w/cpp/chrono/system_clock.html',1,'std::chrono']]],
  ['system_5ferror_73',['system_error',['http://en.cppreference.com/w/cpp/error/system_error.html',1,'std']]]
];
