var searchData=
[
  ['valid_0',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['../classlibsemigroups_1_1_word_range.html#a99f77f09f364b20c3a30ab6bffa4c24b',1,'libsemigroups::WordRange::valid()']]],
  ['validate_1',['validate',['../classlibsemigroups_1_1_presentation.html#ab3a68a01a1c7c22bfbd9f3f6d20e7d5a',1,'libsemigroups::Presentation::validate()'],['../classlibsemigroups_1_1_inverse_presentation.html#ab3a68a01a1c7c22bfbd9f3f6d20e7d5a',1,'libsemigroups::InversePresentation::validate()'],['../namespacelibsemigroups_1_1blocks.html#a757e995c21568feb875f500cc3dbd16e',1,'libsemigroups::blocks::validate()'],['../namespacelibsemigroups_1_1bipartition.html#a04fb3bdd5b176e7f868b17f550ca1139',1,'libsemigroups::bipartition::validate()'],['../group__transf__group.html#gaec19a0378e74f34554609c932f1ea3a9',1,'libsemigroups::validate(T const &amp;f) -&gt; std::enable_if_t&lt; IsPTransf&lt; T &gt; &gt;'],['../group__transf__group.html#ga165dadbfb7f1c29dea22ae37617976cd',1,'libsemigroups::validate(Transf&lt; N, Scalar &gt; const &amp;f)'],['../group__transf__group.html#gac71f287f6e14090323eeb7962697331d',1,'libsemigroups::validate(PPerm&lt; N, Scalar &gt; const &amp;f)'],['../group__transf__group.html#gae7fccde0007cc3f499ec3d31335ece43',1,'libsemigroups::validate(Perm&lt; N, Scalar &gt; const &amp;f)']]],
  ['validate_5factive_5fnode_5findex_2',['validate_active_node_index',['../classlibsemigroups_1_1_aho_corasick.html#ab0c024b0b267a446740fee6ec494dcef',1,'libsemigroups::AhoCorasick']]],
  ['validate_5falphabet_3',['validate_alphabet',['../classlibsemigroups_1_1_presentation.html#a85885d8a4c1acbb575dad4aa0a8d9d59',1,'libsemigroups::Presentation']]],
  ['validate_5fletter_4',['validate_letter',['../classlibsemigroups_1_1_presentation.html#a3bb4217863b66992b475a981b801bab5',1,'libsemigroups::Presentation']]],
  ['validate_5fnode_5findex_5',['validate_node_index',['../classlibsemigroups_1_1_aho_corasick.html#a0587a21a4c12958c310fea28c748f990',1,'libsemigroups::AhoCorasick']]],
  ['validate_5frules_6',['validate_rules',['../classlibsemigroups_1_1_presentation.html#aaebf90ae878d5d3b6142c8dc34c231c9',1,'libsemigroups::Presentation::validate_rules()'],['../namespacelibsemigroups_1_1presentation.html#ae5b4b6eb283afeb6c9d546c7c5988bd4',1,'libsemigroups::presentation::validate_rules(Presentation&lt; Word &gt; const &amp;p, Iterator first, Iterator last)']]],
  ['validate_5fsemigroup_5finverses_7',['validate_semigroup_inverses',['../namespacelibsemigroups_1_1presentation.html#a756f5721e810bac90aca39df8f87c080',1,'libsemigroups::presentation']]],
  ['validate_5fword_8',['validate_word',['../classlibsemigroups_1_1_presentation.html#a16828821733416651369b4c1a1628b61',1,'libsemigroups::Presentation']]],
  ['value_9',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()']]],
  ['value_5fcomp_10',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()']]],
  ['value_5for_11',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['vector_12',['vector',['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector']]],
  ['vfprintf_13',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_14',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_15',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_16',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vprintf_17',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_18',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_19',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_20',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_21',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_22',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_23',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_24',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_25',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
