
// libsemigroups - C++ library for semigroups and monoids
// Copyright (C) 2019-2026 James D. Mitchell
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#define CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS

#include <algorithm>   // for any_of
#include <functional>  // for operator!=
#include <list>        // for operator!=
#include <string>      // for basic_string
#include <utility>     // for forward

#include "Catch2-3.14.0/catch_amalgamated.hpp"  // for SourceLineInfo
#include "test-main.hpp"                        // for LIBSEMIGROUPS_...

#include "libsemigroups/alphabet-class.hpp"        // for Alphabet::init
#include "libsemigroups/alphabet-helpers.hpp"      // for add_letter
#include "libsemigroups/cong-common-helpers.hpp"   // for add_generating...
#include "libsemigroups/constants.hpp"             // for operator==
#include "libsemigroups/knuth-bendix-class.hpp"    // for KnuthBendix
#include "libsemigroups/knuth-bendix-helpers.hpp"  // for add_generating...
#include "libsemigroups/obvinf.hpp"                // for is_obviously_i...
#include "libsemigroups/order.hpp"                 // for LenLexCmp, RPOCmp
#include "libsemigroups/presentation.hpp"          // for add_rule, Presentation
#include "libsemigroups/ranges.hpp"                // for LenLexCmp, RPOCmp
#include "libsemigroups/types.hpp"                 // for congruence_kind
#include "libsemigroups/word-graph-helpers.hpp"    // for topological_sort
#include "libsemigroups/word-graph.hpp"            // for WordGraph::target

#include "libsemigroups/detail/aho-corasick-impl.hpp"  // for begin_search_n...
#include "libsemigroups/detail/cong-common-class.hpp"  // for CongruenceComm...
#include "libsemigroups/detail/eigen.hpp"              // for DenseBase
#include "libsemigroups/detail/fmt.hpp"                // for format
#include "libsemigroups/detail/iterator.hpp"           // for operator+
#include "libsemigroups/detail/knuth-bendix-impl.hpp"  // for KnuthBendixImp...
#include "libsemigroups/detail/print.hpp"              // for to_printable
#include "libsemigroups/detail/report.hpp"             // for report_default
#include "libsemigroups/detail/rewriting-system.hpp"   // for RewritingSyste...
#include "libsemigroups/detail/string.hpp"             // for group_digits
#include "libsemigroups/detail/timer.hpp"              // for string_time
#include "libsemigroups/detail/value-guard.hpp"        // for ValueGuard::Va...

namespace libsemigroups {

  using LenLexTrie = detail::RewritingSystemTrie<LenLexCmp>;
  using RPOTrie    = detail::RewritingSystemTrie<RPOCmp>;
  using RevRPOTrie = detail::RewritingSystemTrie<RevRPOCmp>;

  // Takes approx 13s + 15s
  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "159",
                          "MAF: subgroups/8723",
                          "[extreme][maf]") {
    auto rg = ReportGuard(true);

    Presentation<std::string> p;
    p.alphabet("aAbB").contains_empty_word(true);

    presentation::add_rule(p, "aA", "");
    presentation::add_rule(p, "Aa", "");
    presentation::add_rule(p, "bB", "");
    presentation::add_rule(p, "Bb", "");
    presentation::add_rule(p, "aaaaaaaa", "");
    presentation::add_rule(p, "bbbbbbb", "");
    presentation::add_rule(p, "abab", "");
    presentation::add_rule(p, "AbAbAb", "");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb(congruence_kind::onesided, p);

    SECTION("8723") {
      kb.run();
      REQUIRE(kb.rewriting_system().number_of_rules() == 2'765);
      REQUIRE(kb.number_of_classes() == 10'752);
    }

    SECTION("8723.sub") {
      knuth_bendix::add_generating_pair(kb, "aa", "");
      knuth_bendix::add_generating_pair(kb, "Ab", "");

      kb.run();
      REQUIRE(kb.rewriting_system().number_of_rules() == 3'022);
      REQUIRE(kb.number_of_classes() == 448);
    }
  }

  // Generated by MAF
  // Takes about 1min22s
  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "160",
                          "MAF: unknown/G9576",
                          "[extreme][maf]") {
    auto rg = ReportGuard(true);

    Presentation<std::string> p;
    p.alphabet("aAhHfFdDbBiIgGeEcC").contains_empty_word(true);

    presentation::add_rule(p, "aA", "");
    presentation::add_rule(p, "Aa", "");
    presentation::add_rule(p, "hH", "");
    presentation::add_rule(p, "Hh", "");
    presentation::add_rule(p, "fF", "");
    presentation::add_rule(p, "Ff", "");
    presentation::add_rule(p, "dD", "");
    presentation::add_rule(p, "Dd", "");
    presentation::add_rule(p, "bB", "");
    presentation::add_rule(p, "Bb", "");
    presentation::add_rule(p, "iI", "");
    presentation::add_rule(p, "Ii", "");
    presentation::add_rule(p, "gG", "");
    presentation::add_rule(p, "Gg", "");
    presentation::add_rule(p, "eE", "");
    presentation::add_rule(p, "Ee", "");
    presentation::add_rule(p, "cC", "");
    presentation::add_rule(p, "Cc", "");
    presentation::add_rule(p, "ad", "G");
    presentation::add_rule(p, "ab", "d");
    presentation::add_rule(p, "bc", "e");
    presentation::add_rule(p, "cd", "f");
    presentation::add_rule(p, "de", "g");
    presentation::add_rule(p, "ef", "h");
    presentation::add_rule(p, "fg", "i");
    presentation::add_rule(p, "gh", "a");
    presentation::add_rule(p, "hi", "b");
    presentation::add_rule(p, "ia", "c");
    presentation::add_rule(p, "aDGE", "DBg");  // codespell:ignore

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb(congruence_kind::twosided, p);
    kb.run();
    REQUIRE(kb.rewriting_system().number_of_rules() == 26'675);
    REQUIRE(kb.number_of_classes() == 9'576);
  }

  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "161",
                          "MAF: onerelq/q33_uv",
                          "[extreme][maf][onerelq]") {
    auto rg = ReportGuard(true);

    Presentation<std::string> p;
    p.alphabet("uUvV").contains_empty_word(true);

    presentation::add_rule(p, "uU", "");
    presentation::add_rule(p, "Uu", "");
    presentation::add_rule(p, "vV", "");
    presentation::add_rule(p, "Vv", "");
    presentation::add_rule(p, "vUvvUv", "");
    presentation::add_rule(p, "UvUvUv", "");
    presentation::add_rule(p, "uuuuvvuuvvvvuuvuvv", "");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb;

    // SECTION("q33_uv") {  // fails 30s
    //   kb.init(congruence_kind::twosided, p);
    //   kb.run();
    //   REQUIRE(kb.rewriting_system().number_of_rules() == 0);
    //   REQUIRE(kb.number_of_classes() == POSITIVE_INFINITY);
    // }

    // SECTION("q33_uv.sub") {  // fails 10s
    //   kb.init(congruence_kind::onesided, p);
    //   knuth_bendix::add_generating_pair(kb, "uv", "");

    //   kb.run();
    //   REQUIRE(kb.rewriting_system().number_of_rules() == 0);
    //   REQUIRE(kb.number_of_classes() == POSITIVE_INFINITY);
    // }

    SECTION("q33_uv.sub1") {
      kb.init(congruence_kind::twosided, p);
      knuth_bendix::add_generating_pair(kb, "uuuuuu", "");

      kb.run();
      REQUIRE(kb.rewriting_system().number_of_rules() == 64);
      REQUIRE(kb.number_of_classes() == 114);
    }

    // SECTION("q33_uv.sub2") {  // fails 10s
    //   kb.init(congruence_kind::onesided, p);
    //   knuth_bendix::add_generating_pair(kb, "uvuvuvuvuvuv", "");
    //   knuth_bendix::add_generating_pair(kb, "VUVUVUVUVUVU", "");
    //   knuth_bendix::add_generating_pair(kb, "UVUVUVUVUVUV", "");
    //   knuth_bendix::add_generating_pair(kb, "vuvuvuvuvuvu", "");
    //   knuth_bendix::add_generating_pair(kb, "uuuuuuvvvvvvvu", "");
    //   knuth_bendix::add_generating_pair(kb, "UVVVVVVVUUUUUU", "");
    //   knuth_bendix::add_generating_pair(kb, "UUUUUUVVVVVVVU", "");
    //   knuth_bendix::add_generating_pair(kb, "uvvvvvvvuuuuuu", "");
    //   knuth_bendix::add_generating_pair(kb, "vvvvvvuuuuuuuv", "");
    //   knuth_bendix::add_generating_pair(kb, "VUUUUUUUVVVVVV", "");
    //   knuth_bendix::add_generating_pair(kb, "VVVVVVUUUUUUUV", "");
    //   knuth_bendix::add_generating_pair(kb, "vuuuuuuuvvvvvv", "");
    //   knuth_bendix::add_generating_pair(kb, "uuuuuvvvvvvvuu", "");
    //   knuth_bendix::add_generating_pair(kb, "UUVVVVVVVUUUUU", "");
    //   knuth_bendix::add_generating_pair(kb, "UUUUUVVVVVVVUU", "");
    //   knuth_bendix::add_generating_pair(kb, "uuvvvvvvvuuuuu", "");
    //   knuth_bendix::add_generating_pair(kb, "vvvvvuuuuuuuvv", "");
    //   knuth_bendix::add_generating_pair(kb, "VVUUUUUUUVVVVV", "");
    //   knuth_bendix::add_generating_pair(kb, "VVVVVUUUUUUUVV", "");
    //   knuth_bendix::add_generating_pair(kb, "vvuuuuuuuvvvvv", "");
    //   knuth_bendix::add_generating_pair(kb, "uuuvvvvvvvuuuu", "");
    //   knuth_bendix::add_generating_pair(kb, "UUUUVVVVVVVUUU", "");
    //   knuth_bendix::add_generating_pair(kb, "UUUVVVVVVVUUUU", "");
    //   knuth_bendix::add_generating_pair(kb, "uuuuvvvvvvvuuu", "");
    //   knuth_bendix::add_generating_pair(kb, "vvvuuuuuuuvvvv", "");
    //   knuth_bendix::add_generating_pair(kb, "VVVVUUUUUUUVVV", "");
    //   knuth_bendix::add_generating_pair(kb, "VVVUUUUUUUVVVV", "");
    //   knuth_bendix::add_generating_pair(kb, "vvvvuuuuuuuvvv", "");
    //   knuth_bendix::add_generating_pair(kb, "uuuVVUVUVUVUVV", "");
    //   knuth_bendix::add_generating_pair(kb, "vvuvuvuvuvvUUU", "");
    //   knuth_bendix::add_generating_pair(kb, "UUUvvuvuvuvuvv", "");
    //   knuth_bendix::add_generating_pair(kb, "VVUVUVUVUVVuuu", "");
    //   knuth_bendix::add_generating_pair(kb, "vvvUUVUVUVUVUU", "");
    //   knuth_bendix::add_generating_pair(kb, "uuvuvuvuvuuVVV", "");
    //   knuth_bendix::add_generating_pair(kb, "VVVuuvuvuvuvuu", "");
    //   knuth_bendix::add_generating_pair(kb, "UUVUVUVUVUUvvv", "");
    //   knuth_bendix::add_generating_pair(kb, "uuuuuvuvvvvvvuvu", "");
    //   knuth_bendix::add_generating_pair(kb, "UVUVVVVVVUVUUUUU", "");
    //   knuth_bendix::add_generating_pair(kb, "UUUUUVUVVVVVVUVU", "");
    //   knuth_bendix::add_generating_pair(kb, "uvuvvvvvvuvuuuuu", "");
    //   knuth_bendix::add_generating_pair(kb, "vvvvvuvuuuuuuvuv", "");
    //   knuth_bendix::add_generating_pair(kb, "VUVUUUUUUVUVVVVV", "");
    //   knuth_bendix::add_generating_pair(kb, "VVVVVUVUUUUUUVUV", "");
    //   knuth_bendix::add_generating_pair(kb, "vuvuuuuuuvuvvvvv", "");

    //   kb.run();
    //   REQUIRE(kb.rewriting_system().number_of_rules() == 0);
    //   REQUIRE(kb.number_of_classes() == POSITIVE_INFINITY);
    // }

    SECTION("q33_uv.sub3") {
      kb.init(congruence_kind::twosided, p);
      knuth_bendix::add_generating_pair(kb, "UUUUVVUUVVVVUUVUVV", "");

      kb.run();
      REQUIRE(kb.rewriting_system().number_of_rules() == 2114);
      REQUIRE(kb.number_of_classes() == 6552);
    }

    // SECTION("q33_uv.sub4") {  // fails 10s
    //   kb.init(congruence_kind::onesided, p);
    //   knuth_bendix::add_generating_pair(kb, "v", "");

    //   kb.run();
    //   REQUIRE(kb.rewriting_system().number_of_rules() == 0);
    //   REQUIRE(kb.number_of_classes() == POSITIVE_INFINITY);
    // }
  }
  // A largish finite quotient of the Von Dyck (2,3,7) group
  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "162",
                          "MAF: lesson2/2378",
                          "[extreme][maf][lesson2]") {
    auto rg = ReportGuard(true);

    Presentation<std::string> p;
    p.alphabet("abB").contains_empty_word(true);

    presentation::add_rule(p, "aa", "");
    presentation::add_rule(p, "bB", "");
    presentation::add_rule(p, "Bb", "");
    presentation::add_rule(p, "bb", "B");
    presentation::add_rule(p, "ababababababab", "");
    presentation::add_rule(p, "abaBabaBabaBabaBabaBabaBabaBabaB", "");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb;
    kb.init(congruence_kind::twosided, p);
    kb.run();
    REQUIRE(kb.rewriting_system().number_of_rules() == 1026);
    REQUIRE(kb.number_of_classes() == 10'752);
  }

  // A largish finite quotient of the Von Dyck (3,2,7) group
  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "163",
                          "MAF: lesson2/3278",
                          "[extreme][maf][lesson2]") {
    auto rg = ReportGuard(true);

    Presentation<std::string> p;
    p.alphabet("aAb").contains_empty_word(true);

    presentation::add_rule(p, "aA", "");
    presentation::add_rule(p, "Aa", "");
    presentation::add_rule(p, "bb", "");
    presentation::add_rule(p, "aa", "A");
    presentation::add_rule(p, "ababababababab", "");
    presentation::add_rule(p, "abAbabAbabAbabAbabAbabAbabAbabAb", "");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb;
    kb.init(congruence_kind::twosided, p);
    kb.run();
    REQUIRE(kb.rewriting_system().number_of_rules() == 738);
    REQUIRE(kb.number_of_classes() == 10'752);
  }

  // A largish finite quotient of the Von Dyck (7,2,3) group
  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "164",
                          "MAF: lesson2/7238",
                          "[extreme][maf][lesson2]") {
    auto rg = ReportGuard(true);

    Presentation<std::string> p;
    p.alphabet("aAb").contains_empty_word(true);

    presentation::add_rule(p, "aA", "");
    presentation::add_rule(p, "Aa", "");
    presentation::add_rule(p, "bb", "");
    presentation::add_rule(p, "ababab", "");
    presentation::add_rule(p, "aaaaaaa", "");
    presentation::add_rule(p, "abAbabAbabAbabAbabAbabAbabAbabAb", "");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb;
    kb.init(congruence_kind::twosided, p);
    kb.run();
    REQUIRE(kb.rewriting_system().number_of_rules() == 1'357);
    REQUIRE(kb.number_of_classes() == 10'752);
  }

  // A largish finite quotient of the 2,3,7 Von Dyck group
  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "165",
                          "MAF: lesson2/7238_abc",
                          "[extreme][maf][lesson2]") {
    auto rg = ReportGuard(true);

    Presentation<std::string> p;
    p.alphabet("aAbcC").contains_empty_word(true);

    presentation::add_rule(p, "aA", "");
    presentation::add_rule(p, "Aa", "");
    presentation::add_rule(p, "bb", "");
    presentation::add_rule(p, "cC", "");
    presentation::add_rule(p, "Cc", "");
    presentation::add_rule(p, "abc", "");
    presentation::add_rule(p, "ccc", "");
    presentation::add_rule(p, "aaaaaaa", "");
    presentation::add_rule(p, "abAbabAbabAbabAbabAbabAbabAbabAb", "");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb;
    kb.init(congruence_kind::twosided, p);
    kb.run();
    REQUIRE(kb.rewriting_system().number_of_rules() == 1774);
    REQUIRE(kb.number_of_classes() == 10'752);
  }

  // Fibonacci group F(2,7) - order 29 - works better with largish tidyint
  // takes approx 26s
  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "166",
                          "MAF: Fibonacci/f2_7",
                          "[extreme][maf][Fibonacci]") {
    auto rg = ReportGuard(true);

    Presentation<std::string> p;
    p.alphabet("aAbBcCdDeEfFgG").contains_empty_word(true);

    presentation::add_rule(p, "aA", "");
    presentation::add_rule(p, "Aa", "");
    presentation::add_rule(p, "bB", "");
    presentation::add_rule(p, "Bb", "");
    presentation::add_rule(p, "cC", "");
    presentation::add_rule(p, "Cc", "");
    presentation::add_rule(p, "dD", "");
    presentation::add_rule(p, "Dd", "");
    presentation::add_rule(p, "eE", "");
    presentation::add_rule(p, "Ee", "");
    presentation::add_rule(p, "fF", "");
    presentation::add_rule(p, "Ff", "");
    presentation::add_rule(p, "gG", "");
    presentation::add_rule(p, "Gg", "");
    presentation::add_rule(p, "ab", "c");
    presentation::add_rule(p, "bc", "d");
    presentation::add_rule(p, "cd", "e");
    presentation::add_rule(p, "de", "f");
    presentation::add_rule(p, "ef", "g");
    presentation::add_rule(p, "fg", "a");
    presentation::add_rule(p, "ga", "b");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb;
    kb.init(congruence_kind::twosided, p);
    kb.run();
    REQUIRE(kb.rewriting_system().number_of_rules() == 194);
    REQUIRE(kb.number_of_classes() == 29);
  }

  // quotient? of Von Dyck (2,3,7) group - infinite hyperbolic - small tidyint
  // works better
  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "167",
                          "MAF: both/237q",
                          "[extreme][maf][both]") {
    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("abB").contains_empty_word(true);

    presentation::add_rule(p, "aa", "");
    presentation::add_rule(p, "bB", "");
    presentation::add_rule(p, "Bb", "");
    presentation::add_rule(p, "bb", "B");
    presentation::add_rule(p, "ababababababab", "");
    presentation::add_rule(p, "abaBabaBabaBabaBabaBabaBabaBabaB", "");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb;

    SECTION("237q") {
      kb.init(congruence_kind::twosided, p);
      kb.run();
      REQUIRE(kb.rewriting_system().number_of_rules() == 1026);
      REQUIRE(kb.number_of_classes() == 10752);
    }

    SECTION("237q.sub") {
      kb.init(congruence_kind::onesided, p);
      knuth_bendix::add_generating_pair(kb, "abaBa", "");
      knuth_bendix::add_generating_pair(kb, "babaB", "");
      knuth_bendix::add_generating_pair(kb, "baBaB", "");

      kb.run();
      REQUIRE(kb.rewriting_system().number_of_rules() == 1051);
      REQUIRE(kb.number_of_classes() == 56);
    }
  }

  // Generated by MAF
  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "168",
                          "MAF: balanced/G(-2_-2)comm",
                          "[extreme][maf][balanced]") {
    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("aAbBcC").contains_empty_word(true);

    presentation::add_rule(p, "aA", "");
    presentation::add_rule(p, "Aa", "");
    presentation::add_rule(p, "bB", "");
    presentation::add_rule(p, "Bb", "");
    presentation::add_rule(p, "cC", "");
    presentation::add_rule(p, "Cc", "");
    presentation::add_rule(p, "A", "aaaaaaaaaaaaaaaaaaaaaaaaaa");
    presentation::add_rule(p, "B", "bbbbbbbbaaaaaaaaa");
    presentation::add_rule(p, "C", "ccccccccbbbbbbbbaabaaaaaaaaaaaaaaaa");
    presentation::add_rule(p, "ac", "cbbbbbbbbabaaaaaaaaaaaaaaaaaaaaaaaa");
    presentation::add_rule(p, "bc", "cbbbabaaaaaaaa");
    presentation::add_rule(p, "abb", "baabaaaaaaaaaaaaaaaaaaaaaaaaaa");
    presentation::add_rule(p, "aaab", "baaa");
    presentation::add_rule(p, "abab", "bbaa");
    presentation::add_rule(p, "abaab", "babaa");
    presentation::add_rule(p, "bbbbbbbbb", "aaaaaaaaaaaaaaaaaa");
    presentation::add_rule(
        p, "ccccccccc", "bbbbbbbbabaaaaaaaaaaaaaaaaaaaaaaaaaa");
    presentation::add_rule(p, "aaaaaaaaaaaaaaaaaaaaaaaaaaa", "");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb;
    kb.init(congruence_kind::twosided, p);
    kb.run();
    REQUIRE(kb.rewriting_system().number_of_rules() == 8377);
    REQUIRE(kb.number_of_classes() == 6561);
  }

  LIBSEMIGROUPS_TEST_CASE("KnuthBendix",
                          "169",
                          "MAF: balanced/Mennicke(2_-2_-2)",
                          "[extreme][maf][balanced]") {
    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("aAbBcC").contains_empty_word(true);

    presentation::add_rule(p, "aA", "");
    presentation::add_rule(p, "Aa", "");
    presentation::add_rule(p, "bB", "");
    presentation::add_rule(p, "Bb", "");
    presentation::add_rule(p, "cC", "");
    presentation::add_rule(p, "Cc", "");
    presentation::add_rule(p, "baB", "aa");
    presentation::add_rule(p, "cbC", "BB");
    presentation::add_rule(p, "acA", "CC");

    using RewritingSystem = detail::RewritingSystemTrie<LenLexCmp>;
    KnuthBendix<std::string, RewritingSystem> kb;

    SECTION("Mennicke(2_-2_-2)") {
      kb.init(congruence_kind::twosided, p);
      kb.run();
      REQUIRE(kb.rewriting_system().number_of_rules() == 211);
      REQUIRE(kb.number_of_classes() == 189);
    }

    SECTION("Mennicke(2_-2_-2).sub") {
      kb.init(congruence_kind::onesided, p);
      knuth_bendix::add_generating_pair(kb, "ab", "");
      knuth_bendix::add_generating_pair(kb, "bc", "");

      kb.run();
      REQUIRE(kb.rewriting_system().number_of_rules() == 217);
      REQUIRE(kb.number_of_classes() == 1);
    }
  }

}  // namespace libsemigroups
