//
// libsemigroups - C++ library for semigroups and monoids
// Copyright (C) 2026 James D. Mitchell
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

// The first version of this file was auto-generated by
// etc/generate_1_relation_tests.py

#define CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS

#include <chrono>
#include <string>

#include "tests/test-main.hpp"

#include "libsemigroups/constants.hpp"
#include "libsemigroups/knuth-bendix.hpp"
#include "libsemigroups/presentation.hpp"
#include "libsemigroups/ranges.hpp"
#include "libsemigroups/tietze.hpp"
#include "libsemigroups/to-presentation.hpp"

#include "libsemigroups/detail/report.hpp"
#include "libsemigroups/detail/rewriting-system.hpp"
#include "libsemigroups/detail/rules.hpp"

namespace libsemigroups {

  using RPOTrie    = detail::RewritingSystemTrie<RPOCmp>;
  using RevRPOTrie = detail::RewritingSystemTrie<RevRPOCmp>;
  using LenLexTrie = detail::RewritingSystemTrie<LenLexCmp>;

  LIBSEMIGROUPS_TEST_CASE("1-relation", "350", "aaaabaabba=babaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaaabaabba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "351",
                          "aabaaabba=baaabaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabaaabba", "baaabaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "352",
                          "baabaaaba=abaaba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaaaba", "abaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 5.861s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "353",
                          "abaabbabaa=baaba",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaabbabaa", "baaba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "354",
                          "baabbaaaba=aabbaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbaaaba", "aabbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "355", "baaabbaba=a", "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabbaba", "a");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "356",
                          "baabaabaa=ababaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaabaa", "ababaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "357", "abbabbaaa=babba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbabbaaa", "babba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "358", "baaabbabaa=aabba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabbabaa", "aabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "359", "ababaaabaa=baaba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "ababaaabaa", "baaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "360", "baabaabaa=abaaba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaabaa", "abaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 6.250s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "361",
                          "baaaabaaba=a",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabaaba", "a");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 3.680s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "362",
                          "abbaabbaba=bababbaa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbaabbaba", "bababbaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 6.066s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "363",
                          "aabaabbaba=babaaba",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabaabbaba", "babaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "364", "aabaababaa=baabaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabaababaa", "baabaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 6.382s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "365",
                          "abaababbaa=baaba",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaababbaa", "baaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "366", "aaababaaba=babaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaababaaba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 7.623s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "367",
                          "baaababaaa=abaaaba",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaababaaa", "abaaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "368", "aababbbaba=babbaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aababbbaba", "babbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 8.375s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "369",
                          "ababbabbaa=babbaaba",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "ababbabbaa", "babbaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "370",
                          "baaababaaa=aababaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaababaaa", "aababaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "371",
                          "baaabaaaba=abaaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabaaaba", "abaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "372",
                          "abbabbaaba=babba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbabbaaba", "babba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "373",
                          "baaaaabba=abaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaaabba", "abaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "374",
                          "abaabababa=babaabaa",
                          "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaabababa", "babaabaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "375", "baabaabba=abaa", "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaabba", "abaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "376", "abaabababa=babaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaabababa", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "377", "babaababaa=ababa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babaababaa", "ababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "378",
                          "baabaaaba=aaabbaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaaaba", "aaabbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "379", "baaaabaaba=aabaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabaaba", "aabaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "380",
                          "bbaaaabba=abbaaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "bbaaaabba", "abbaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "381",
                          "babbaaaba=ababba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babbaaaba", "ababba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "382",
                          "aaabbababa=babaaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaabbababa", "babaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "383", "bababbbbba=aba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "bababbbbba", "aba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "384",
                          "abaabaaaba=baabaaa",
                          "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaabaaaba", "baabaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "385", "bbaaabbbba=aa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "bbaaabbbba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "386", "baabaaabaa=aba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaaabaa", "aba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "387",
                          "baabbababa=abba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbababa", "abba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "388",
                          "babaabaaba=aabbaba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babaabaaba", "aabbaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "389",
                          "baaababaa=aababa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaababaa", "aababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 4.543s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "390",
                          "abaaabbaba=babaaaba",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaaabbaba", "babaaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "391",
                          "bababaaba=ababa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "bababaaba", "ababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "392",
                          "baababbaba=a",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baababbaba", "a");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "393",
                          "babaaaabba=ababaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babaaaabba", "ababaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 4.861s.
  LIBSEMIGROUPS_TEST_CASE("1-relation", "394", "baaaababa=abbaa", "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaababa", "abbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 18.644s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "395",
                          "baaababba=aa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaababba", "aa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "396", "abaaaababa=babaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaaaababa", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 4.490s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "397",
                          "abbabbbbaa=bbaabba",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbabbbbaa", "bbaabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "398",
                          "abaabaaaba=baabaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaabaaaba", "baabaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 8.148s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "399",
                          "ababaaabba=babaaa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "ababaaabba", "babaaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

}  // namespace libsemigroups
