//
// libsemigroups - C++ library for semigroups and monoids
// Copyright (C) 2026 James D. Mitchell
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

// The first version of this file was auto-generated by
// etc/generate_1_relation_tests.py

#define CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS

#include <chrono>
#include <string>

#include "tests/test-main.hpp"

#include "libsemigroups/constants.hpp"
#include "libsemigroups/du-narendran-rusinowitch.hpp"
#include "libsemigroups/knuth-bendix.hpp"
#include "libsemigroups/presentation.hpp"
#include "libsemigroups/ranges.hpp"
#include "libsemigroups/tietze.hpp"
#include "libsemigroups/to-presentation.hpp"

#include "libsemigroups/detail/report.hpp"
#include "libsemigroups/detail/rewriting-system.hpp"
#include "libsemigroups/detail/rules.hpp"

namespace libsemigroups {

  using RPOTrie    = detail::RewritingSystemTrie<RPOCmp>;
  using RevRPOTrie = detail::RewritingSystemTrie<RevRPOCmp>;
  using LenLexTrie = detail::RewritingSystemTrie<LenLexCmp>;

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "000",
                          "ababbaaaaa=baaaaaba",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "ababbaaaaa", "baaaaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(6).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.value().alphabet() == "cadb");
    REQUIRE(
        result.value().rules
        == std::vector<std::string>({"ad", "cba", "c", "baaaaa", "d", "babc"}));
    kb.init(congruence_kind::twosided, result.value());
    kb.run();
    REQUIRE(kb.rewriting_system().confluent());

    using rule_type = typename decltype(kb)::rule_type;
    REQUIRE((kb.active_rules() | rx::to_vector())
            == std::vector<rule_type>({{"babc", "d"},
                                       {"baaaaa", "c"},
                                       {"cba", "ad"},
                                       {"babad", "dba"},
                                       {"adbc", "cd"},
                                       {"adaaaa", "cc"},
                                       {"baaaacd", "cdbc"},
                                       {"baaaacc", "cdaaaa"},
                                       {"adbad", "cdba"},
                                       {"cbcd", "addbc"},
                                       {"cbcc", "addaaaa"},
                                       {"ccdbc", "adaaacd"},
                                       {"ccdaaaa", "adaaacc"},
                                       {"baaaacad", "cdaaaaba"},
                                       {"cbcad", "addaaaaba"},
                                       {"ccdbad", "adaaacdba"}}));
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "001", "aabaababba=baaba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabaababba", "baaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "002",
                          "abbabbaaaa=babba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbabbaaaa", "babba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "003", "babbabaaba=abba", "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babbabaaba", "abba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "004",
                          "baabbaaaba=aabba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbaaaba", "aabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "005", "baaaaabbba=aaaaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaaabbba", "aaaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "006",
                          "abaabaabaa=baaba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaabaabaa", "baaba");

    KnuthBendix<std::string, LenLexTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(6).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "007", "abaaabaaba=babaaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaaabaaba", "babaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "008",
                          "aabaaaabba=baaabaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabaaaabba", "baaabaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "009",
                          "babbbaba=abbba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babbbaba", "abbba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(6).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "010", "baaaaabbba=abaa", "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaaabbba", "abaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "011",
                          "babaaababa=aabababa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babaaababa", "aabababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "012", "bababbba=aba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "bababbba", "aba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "013",
                          "ababaaabba=baaababa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "ababaaabba", "baaababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "014",
                          "babbaababa=abba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babbaababa", "abba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "015",
                          "baabaabbaa=abbaaba",
                          "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaabbaa", "abbaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "016", "baaaabbbaa=aaaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabbbaa", "aaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "017",
                          "aababbabba=babaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aababbabba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "018",
                          "aaabaaabba=baaabaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaabaaabba", "baaabaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "019",
                          "baababbaa=abbaaba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baababbaa", "abbaaba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "020",
                          "aaabaabbaa=baaaba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaabaabbaa", "baaaba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "021",
                          "aaaabaabba=baabaaa",
                          "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaaabaabba", "baabaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "022",
                          "baaaabbaba=a",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabbaba", "a");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "023", "baaabbbbba=aa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabbbbba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "024",
                          "baaabaaaba=abbaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabaaaba", "abbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "025",
                          "abbababaaa=baabba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbababaaa", "baabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "026",
                          "baaabaabaa=ababa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabaabaa", "ababa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "027",
                          "abbabaaba=baba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbabaaba", "baba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "028",
                          "aaabababba=babaaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaabababba", "babaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "029", "abbabbaa=baba", "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbabbaa", "baba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "030",
                          "baabbaabba=abababa",
                          "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbaabba", "abababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "031", "aaaabababa=babaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaaabababa", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "032",
                          "baaabababa=abbaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabababa", "abbaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "033",
                          "baabaabba=abaaba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaabba", "abaaba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "034",
                          "baaaabbbaa=abaaa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabbbaa", "abaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "035",
                          "baabaaabba=abbaaba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaaabba", "abbaaba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "036",
                          "aababbaaaa=baaaaaba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aababbaaaa", "baaaaaba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "037", "baaaabbbaa=aba", "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabbbaa", "aba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "038",
                          "babaabbbba=abbbbaba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babaabbbba", "abbbbaba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "039",
                          "abbababbaa=baba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbababbaa", "baba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(6).proper(true));

    auto num = (input | rx::count());

    REQUIRE(num == 19'853'625);

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(1));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if.total(num)).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "040", "baabbaabba=aa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbaabba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "041",
                          "aabbaabbba=baabbaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabbaabbba", "baabbaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "042", "baabababba=a", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabababba", "a");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(2).proper(true));

    auto num = (input | rx::count());

    REQUIRE(num != 0);

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if.total(num)).get();

    REQUIRE(result.has_value());
    REQUIRE(result.value().alphabet() == "bcda");
    REQUIRE(result.value().rules
            == std::vector<std::string>({"caccbc", "a", "c", "ba", "d", "aa"}));
    kb.init(congruence_kind::twosided, result.value());
    kb.run();
    REQUIRE(kb.rewriting_system().confluent());

    using rule_type = typename decltype(kb)::rule_type;
    REQUIRE((kb.active_rules() | rx::to_vector())
            == std::vector<rule_type>({{"bdccc", "dccbc"},
                                       {"a", "bdccbc"},
                                       {"cbdccbc", "bd"},
                                       {"bbdccbc", "c"},
                                       {"bdccbbd", "d"},
                                       {"bdcbd", "dccc"},
                                       {"bdccbd", "dccbbd"},
                                       {"bdbd", "dcccccbc"},
                                       {"cd", "dcccccbcccbc"},
                                       {"bdd", "dcccccbcccbbd"}}));
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "043", "baaabbabba=aa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabbabba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "044",
                          "aabababa=babaaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabababa", "babaaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // Takes ~7 seconds
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "045",
                          "baabbaabaa=aabbaa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbaabaa", "aabbaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(3).max_length(3).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(1));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto num = (input | rx::count());

    REQUIRE(num != 0);

    auto result = (input | find_if.total(num)).get();

    REQUIRE(result.has_value());
    // Non-deterministic, so output not checked
    // REQUIRE(result.value().alphabet() == "bedca");
    // REQUIRE(result.value().rules
    //         == std::vector<std::string>(
    //             {"dcaa", "cbaa", "c", "aab", "d", "bcb", "e", "bcc"}));
    // kb.init(congruence_kind::twosided, result.value());
    // kb.run();
    // REQUIRE(kb.rewriting_system().confluent());

    // using rule_type = typename decltype(kb)::rule_type;
    // REQUIRE((kb.active_rules() | rx::to_vector())
    //         == std::vector<rule_type>({{"aab", "c"},
    //                                    {"bcc", "e"},
    //                                    {"bcb", "d"},
    //                                    {"aad", "ccb"},
    //                                    {"aae", "ccc"},
    //                                    {"cbc", "bce"},
    //                                    {"aacbaa", "bceeaa"},
    //                                    {"aacbac", "bceeac"},
    //                                    {"ccd", "bceeb"},
    //                                    {"bceec", "cce"},
    //                                    {"dc", "bbce"},
    //                                    {"bcec", "ce"},
    //                                    {"bceb", "cd"},
    //                                    {"ebc", "bbcee"},
    //                                    {"cbbce", "dbcee"},
    //                                    {"bbceabce", "cbabce"},
    //                                    {"bbceac", "cbac"},
    //                                    {"bbceaa", "cbaa"},
    //                                    {"aacce", "cceec"},
    //                                    {"aacd", "cceb"},
    //                                    {"aace", "ccec"},
    //                                    {"aacbadbcee", "bceeadbcee"},
    //                                    {"aacbabce", "bceeabce"},
    //                                    {"ccce", "bceeec"},
    //                                    {"ccebbce", "bceedbcee"},
    //                                    {"ccbaa", "dbceeaa"},
    //                                    {"ccbac", "dbceeac"},
    //                                    {"ccbabce", "dbceeabce"},
    //                                    {"dbceeec", "cee"},
    //                                    {"dbceeb", "bced"},
    //                                    {"ecce", "bbceeeec"},
    //                                    {"ecd", "bbceeeb"},
    //                                    {"bbceeec", "ece"},
    //                                    {"bbceeb", "ed"},
    //                                    {"dbceaa", "ebaa"},
    //                                    {"dbceac", "ebac"},
    //                                    {"dbceabce", "ebabce"},
    //                                    {"dbceeeec", "cece"},
    //                                    {"dbceeeb", "ced"},
    //                                    {"bdbcee", "dbce"},
    //                                    {"bbceadbcee", "cbadbcee"},
    //                                    {"bcdbce", "ddbcee"},
    //                                    {"ddbceee", "ebbce"},
    //                                    {"ccecbaa", "bceedbceeaa"},
    //                                    {"ccecbac", "bceedbceeac"},
    //                                    {"ccecbabce", "bceedbceeabce"},
    //                                    {"ccbadbcee", "dbceeadbcee"},
    //                                    {"ecebbce", "bbceeedbcee"},
    //                                    {"ddbceeaa", "cdaa"},
    //                                    {"ddbceeac", "cdac"},
    //                                    {"ddbceeabce", "cdabce"},
    //                                    {"dbceadbcee", "ebadbcee"},
    //                                    {"ececbaa", "bbceeedbceeaa"},
    //                                    {"ececbac", "bbceeedbceeac"},
    //                                    {"ececbabce", "bbceeedbceeabce"},
    //                                    {"ccecbadbcee", "bceedbceeadbcee"},
    //                                    {"dbceedbce", "bceddbcee"},
    //                                    {"dbceeedbce", "ceddbcee"},
    //                                    {"bcedbce", "cddbcee"},
    //                                    {"bbceedbce", "eddbcee"},
    //                                    {"ececbadbcee", "bbceeedbceeadbcee"},
    //                                    {"ddbceeadbcee", "cdadbcee"}}));
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "046",
                          "abbabaabba=babababa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbabaabba", "babababa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(8).proper(true));

    auto num = (input | rx::count());

    REQUIRE(num != 0);

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if.total(num)).get();

    REQUIRE(result.has_value());
    REQUIRE(result.value().rules
            == std::vector<std::string>(
                {"dcaa", "cbaa", "c", "aab", "d", "bcb", "e", "bcc"}));
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "047",
                          "ababbababa=babababa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "ababbababa", "babababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "048",
                          "abbababbba=baba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbababbba", "baba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "049", "baabaabba=a", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaabba", "a");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

}  // namespace libsemigroups
