//
// libsemigroups - C++ library for semigroups and monoids
// Copyright (C) 2026 James D. Mitchell
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

// The first version of this file was auto-generated by
// etc/generate_1_relation_tests.py

#define CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS

#include <chrono>
#include <string>

#include "tests/test-main.hpp"

#include "libsemigroups/constants.hpp"
#include "libsemigroups/knuth-bendix.hpp"
#include "libsemigroups/presentation.hpp"
#include "libsemigroups/ranges.hpp"
#include "libsemigroups/tietze.hpp"
#include "libsemigroups/to-presentation.hpp"

#include "libsemigroups/detail/report.hpp"
#include "libsemigroups/detail/rewriting-system.hpp"
#include "libsemigroups/detail/rules.hpp"

namespace libsemigroups {

  using RPOTrie    = detail::RewritingSystemTrie<RPOCmp>;
  using RevRPOTrie = detail::RewritingSystemTrie<RevRPOCmp>;
  using LenLexTrie = detail::RewritingSystemTrie<LenLexCmp>;

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "050",
                          "babaabaaba=aabbabaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babaabaaba", "aabbabaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "051", "baaaaaabba=aaaaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaaaabba", "aaaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "052",
                          "abaabbabba=babbaaba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaabbabba", "babbaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 3.007s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "053",
                          "baaababbaa=abababa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaababbaa", "abababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "054", "bbaaabbaaa=abbaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "bbaaabbaaa", "abbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "055", "baabaabbba=aa", "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaabbba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "056",
                          "abbabbabaa=baba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbabbabaa", "baba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 14.235s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "057",
                          "abaabbbaba=babaa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaabbbaba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "058",
                          "baabbaaaba=abbaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbaaaba", "abbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "059", "abbabbbaba=babba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbabbbaba", "babba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "060", "baabbbabba=a", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbbabba", "a");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "061",
                          "baaababbba=abaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaababbba", "abaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "062", "baabbbbba=aa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbbbba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "063",
                          "baaaababa=aa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaababa", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "064",
                          "aaaabababa=babaaaaa",
                          "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaaabababa", "babaaaaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "065",
                          "bbaabbabba=abbaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "bbaabbabba", "abbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "066",
                          "abababbba=baba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abababbba", "baba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "067",
                          "baaaaabba=aabaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaaabba", "aabaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "068", "baaaabbba=aa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabbba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "069",
                          "abaabaabba=babaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaabaabba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 5.213s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "070",
                          "abababbaaa=baababa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abababbaaa", "baababa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "071",
                          "baababbba=aba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baababbba", "aba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "072", "baaaaabbba=aaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaaabbba", "aaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "073",
                          "baaabaabba=a",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabaabba", "a");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "074", "abaababaa=baaba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaababaa", "baaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "075",
                          "baaababba=aba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaababba", "aba");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "076", "baaaabbbba=aa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabbbba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "077",
                          "aabbabbaba=babaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabbabbaba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "078", "baaaabbbba=aaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabbbba", "aaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "079",
                          "baaabaaaba=aaabbaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaabaaaba", "aaabbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "080", "aaaababbaa=babaaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaaababbaa", "babaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 13.546s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "081",
                          "aabaababba=baabaa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabaababba", "baabaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "082", "abbaaabbaa=babba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbaaabbaa", "babba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 3.686s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "083",
                          "baabaabbaa=aabbaaba",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaabbaa", "aabbaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "084",
                          "baabbbabaa=aabbba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbbabaa", "aabbba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "085",
                          "bbaaaabbaa=abbaaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "bbaaaabbaa", "abbaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "086",
                          "aaabbbaaba=baabbaa",
                          "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aaabbbaaba", "baabbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "087",
                          "baaaaabbaa=aaba",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaaabbaa", "aaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "088",
                          "bbaaabbbba=abbaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "bbaaabbbba", "abbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "089", "baabbaabba=aba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabbaabba", "aba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "090",
                          "abbbaababa=baabbbaa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbbaababa", "baabbbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  // This extreme test passed in 11.222s.
  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "091",
                          "abaaabbaba=babaa",
                          "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abaaabbaba", "babaa");

    KnuthBendix<std::string, RevRPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<3>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "092",
                          "abbaababba=bababbaa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "abbaababba", "bababbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "093", "aabaaaabba=babaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "aabaaaabba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "094", "baaaabba=aa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "095",
                          "babbabbbba=abba",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "babbabbbba", "abba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "096",
                          "baabaabbaa=abababa",
                          "[standard]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baabaabbaa", "abababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "097", "baababbbaa=aaba", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baababbbaa", "aaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation", "098", "baaaabba=aaa", "[quick]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baaaabba", "aaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(4).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE("1-relation",
                          "099",
                          "baababbaa=abababa",
                          "[extreme][fail]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(p, "baababbaa", "abababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input
        = (p | pedersen_pestov<2>(kb).min_length(2).max_length(9).proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

}  // namespace libsemigroups
