//
// libsemigroups - C++ library for semigroups and monoids
// Copyright (C) 2026 James D. Mitchell
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

// The first version of this file was auto-generated by etc/generate_1_relation_tests.py

#define CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS

#include <chrono>
#include <string>

#include "tests/test-main.hpp"

#include "libsemigroups/constants.hpp"
#include "libsemigroups/knuth-bendix.hpp"
#include "libsemigroups/presentation.hpp"
#include "libsemigroups/ranges.hpp"
#include "libsemigroups/tietze.hpp"
#include "libsemigroups/to-presentation.hpp"

#include "libsemigroups/detail/report.hpp"
#include "libsemigroups/detail/rewriting-system.hpp"
#include "libsemigroups/detail/rules.hpp"

namespace libsemigroups {

  using RPOTrie = detail::RewritingSystemTrie<RPOCmp>;
  using RevRPOTrie = detail::RewritingSystemTrie<RevRPOCmp>;
  using LenLexTrie = detail::RewritingSystemTrie<LenLexCmp>;

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "300",
      "aabbaabbba=baabba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "aabbaabbba", "baabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "301",
      "abaabababa=babaaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abaabababa", "babaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "302",
      "babaabbbba=aba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "babaabbbba", "aba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "303",
      "abbababaa=baabba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abbababaa", "baabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "304",
      "baabaaabaa=aaabba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baabaaabaa", "aaabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "305",
      "baaaabbaa=abaaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baaaabbaa", "abaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "306",
      "aabababbaa=baaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "aabababbaa", "baaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "307",
      "baabbbbbba=aa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baabbbbbba", "aa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "308",
      "baabbaa=aabba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baabbaa", "aabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "309",
      "baaaaababa=abbaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baaaaababa", "abbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "310",
      "babaababa=abababa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "babaababa", "abababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "311",
      "aaabaaabba=baaabaaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "aaabaaabba", "baaabaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "312",
      "baaaabbaba=abaaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baaaabbaba", "abaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "313",
      "abaabbaaaa=baaaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abaabbaaaa", "baaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "314",
      "abbabaabba=baabbaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abbabaabba", "baabbaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "315",
      "aaaabbaaba=baabaaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "aaaabbaaba", "baabaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "316",
      "baaaaaabba=abaaaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baaaaaabba", "abaaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "317",
      "bababbaaba=ababba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "bababbaaba", "ababba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "318",
      "baababba=a",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baababba", "a");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "319",
      "baababbaba=aba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baababbaba", "aba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "320",
      "baaaababa=a",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baaaababa", "a");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "321",
      "baabbaabaa=abaabbaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baabbaabaa", "abaabbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "322",
      "abaabaaba=baabaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abaabaaba", "baabaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "323",
      "aaaaababba=babaaaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "aaaaababba", "babaaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "324",
      "baabaaba=aabba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baabaaba", "aabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "325",
      "abaaaababa=baaabaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abaaaababa", "baaabaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "326",
      "baaaabbaaa=aaaabbaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baaaabbaaa", "aaaabbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "327",
      "abaabbaba=babaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abaabbaba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "328",
      "abbabbbba=babba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abbabbbba", "babba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "329",
      "babaaabbba=aabbbaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "babaaabbba", "aabbbaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "330",
      "abaaababba=babaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abaaababba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "331",
      "abaabaaaba=baaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abaabaaaba", "baaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "332",
      "abababaaaa=baaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abababaaaa", "baaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "333",
      "aababababa=babaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "aababababa", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "334",
      "abbabbbaaa=baaabba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abbabbbaaa", "baaabba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "335",
      "baaabbbaba=abaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baaabbbaba", "abaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "336",
      "baababbbaa=abba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baababbbaa", "abba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "337",
      "baaaabbaa=abaaaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baaaabbaa", "abaaaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "338",
      "abaabaaaba=babaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abaabaaaba", "babaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "339",
      "aaabaaabba=baaaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "aaabaaabba", "baaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "340",
      "baabababaa=aaaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baabababaa", "aaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "341",
      "abaaaabbaa=baaaaaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "abaaaabbaa", "baaaaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "342",
      "babaababba=ababa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "babaababba", "ababa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "343",
      "baabaabbaa=abaaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baabaabbaa", "abaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "344",
      "babbbabba=abbba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "babbbabba", "abbba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "345",
      "baabbaa=aba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baabbaa", "aba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "346",
      "baababbaa=abaaba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baababbaa", "abaaba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "347",
      "ababbbabba=baba",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "ababbbabba", "baba");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "348",
      "baaaabbaba=abaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "baaaabbaba", "abaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

  LIBSEMIGROUPS_TEST_CASE(
      "1-relation",
      "349",
      "bbbaaabbba=abbbaa",
      "[extreme]") {
    using rx::operator|;

    auto rg = ReportGuard(false);

    Presentation<std::string> p;
    p.alphabet("ab");
    p.contains_empty_word(true);
    presentation::add_rule(
        p, "bbbaaabbba", "abbbaa");

    KnuthBendix<std::string, RPOTrie> kb(congruence_kind::twosided, p);

    auto input = (p | pedersen_pestov<2>(kb)
                          .min_length(2)
                          .max_length(4)
                          .proper(true));

    auto find_if = FindIf([kb](auto const& p) mutable {
                     kb.init(congruence_kind::twosided, p);
                     kb.run_for(std::chrono::milliseconds(2));
                     return kb.rewriting_system().confluent();
                   }).number_of_threads(8);

    auto result = (input | find_if).get();

    REQUIRE(result.has_value());
  }

}
