name: Compilers
on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.compiler }}-${{ matrix.version }}
    timeout-minutes: 60
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: "g++"
            version: [9, 10, 11, 12, 13, 14]
          - compiler: "clang++"
            version: [14, 15, 16, 17, 18, 19]
    steps:
      - uses: actions/checkout@v3
      - name: "Setup ccache . . ."
        uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          install_ccache: true
      - name: "Setup compiler . . ."
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
          sudo apt-get --yes update
          sudo apt-get install ${{ matrix.compiler }}-${{ matrix.version }}
          CXX=${{ matrix.compiler }}-${{ matrix.version }}
          echo "CXX=$CXX" >> $GITHUB_ENV
      - name: "Compiler information"
        run: |
          echo $CXX
          $CXX --version
      - name: "Configure . . ."
        env:
          CXX: ${{ env.CXX }}
        run: |
          mkdir -p m4
          ./autogen.sh 
          ./configure CXX="$CXX" --disable-hpcombi
      - name: "Build libsemigroups . . ."
        run: make -j4
      - name: "Build test_all . . ."
        run: make test_all -j4
      - name: "Run the quick and standard tests . . ."
        run: ./test_all "[quick],[standard]"
