name: Downstream
on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    env:
      CC: ccache gcc
      CXX: ccache g++
      # The CXXFLAGS below must be set to -O0 because o/w this CI job fails
      # with a library loading issue (related to fmt). The flag -O3 is set
      # in libsemigroups/Makefile.am, and removing that also resolves this
      # issue. JDM also tried with -O1/2 and this didn't work either.
      CXXFLAGS: -fdiagnostics-color -O0
      CONFIG_FLAGS:
      URL: https://github.com/libsemigroups/libsemigroups_pybind11.git
      LD_LIBRARY_PATH: /usr/local/lib/
    name: libsemigroups_pybind11 / main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout libsemigroups
        uses: actions/checkout@v6
      - name: Install git + autotools
        run: |
          sudo apt-get --yes update
          sudo apt-get install git --yes
          sudo apt-get install pkg-config m4 libtool automake autoconf --yes
          sudo apt-get install libtool-bin --yes
      - name: Setup ccache . . .
        uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          install_ccache: true
      - name: Configure libsemigroups . . .
        run: |
          mkdir -p m4
          ./autogen.sh
          ./configure CXX="$CXX" CXXFLAGS="$CXXFLAGS" $CONFIG_FLAGS
      - name: Build libsemigroups . . .
        run: sudo make install -j4
      - name: Clone libsemigroups_pybind11 . . .
        run: git clone "$URL" --depth 1 --branch main
      - name: Install prerequisites for libsemigroups_pybind11 . . .
        run: |
          cd libsemigroups_pybind11
          sudo apt-get --yes update
          sudo apt-get install python3 --yes
          sudo apt-get install python3-pip --yes
          pip3 install -r requirements.txt
      - name: Building libsemigroups_pybind11 . . .
        run: |
          cd libsemigroups_pybind11
          pip3 install .
      - name: Running libsemigroups_pybind11 tests. . .
        run: |
          cd libsemigroups_pybind11
          make check
  GAP:
    env:
      GAP_VERSION: "4.15.1"
      GAP_SEMIGROUPS_REPO: "semigroups"
      GAP_SEMIGROUPS_BRANCH: "stable-5.6"
      GAP: "gap -A -T --quitonbreak"
      GAP_DIR: "/home/runner/gap"
      CONFIGFLAGS: "--disable-hpcombi"
    name: GAP 4.15.1 / Semigroups / stable-5.6 / ubuntu / 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Install GAP"
        uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ env.GAP_VERSION }}
      - name: "Clone the Semigroups GAP package"
        run: |
          rm -rf $GAP_DIR/pkg/semigroups-*.*.*
          cd $GAP_DIR/pkg
          git clone -b $GAP_SEMIGROUPS_BRANCH --depth=1 https://github.com/$GAP_SEMIGROUPS_REPO/Semigroups.git Semigroups
          cp -r $GITHUB_WORKSPACE Semigroups
      - name: "Build the Semigroups GAP package"
        run: |
          cd $GAP_DIR/pkg/Semigroups
          cp .LIBSEMIGROUPS_VERSION libsemigroups/.VERSION 
          ./autogen.sh
          ./configure $CONFIGFLAGS
          make -j4
      - name: "Build Semigroup GAP package dependencies"
        shell: bash
        run: |
          echo "LoadPackage(\"PackageManager\"); QuitGap(InstallPackage(\"autodoc\", false));" | $GAP
          echo "LoadPackage(\"PackageManager\"); QuitGap(InstallPackage(\"datastructures\", false));" | $GAP
          echo "LoadPackage(\"PackageManager\"); QuitGap(InstallPackage(\"digraphs\", false));" | $GAP
          echo "LoadPackage(\"PackageManager\"); QuitGap(InstallPackage(\"genss\", false));" | $GAP
          echo "LoadPackage(\"PackageManager\"); QuitGap(InstallPackage(\"images\", false));" | $GAP
          echo "LoadPackage(\"PackageManager\"); QuitGap(InstallPackage(\"orb\", false) and CompilePackage(\"orb\"));" | $GAP
      - name: "Run Semigroups package's tst/teststandard.g"
        run: |
          cd $GAP_DIR/pkg/Semigroups
          $GAP tst/teststandard.g
      - name: "Run Semigroups GAP package workspace tests"
        run: |
          cd $GAP_DIR/pkg/Semigroups
          $GAP tst/workspaces/save.g
          $GAP -L tst/workspaces/test-output.w tst/workspaces/load.g
      - name: "Run GAP testinstall"
        run: |
          cd $GAP_DIR/pkg/Semigroups
          $GAP ci/run-gap-testinstall.g
      - name: "Run GAP teststandard"
        run: |
          cd $GAP_DIR
          rm -f tst/teststandard/ctblsymm.tst
          cd pkg/Semigroups
          $GAP ci/run-gap-teststandard.g
      - name: "Run GAP testbugfix"
        run: |
          cd $GAP_DIR
          rm -f tst/testbugfix/2005-05-03-t00061.tst
          rm -f tst/testbugfix/2016-03-03-t00332.tst
          rm -f tst/testbugfix/2018-05-24-IntermediateSubgroups.tst
          rm -f tst/testbugfix/2018-09-13-MTC.tst
          rm -f tst/testbugfix/2018-12-06-GroupWithGenerators.tst
          cd pkg/Semigroups
          $GAP ci/run-gap-testbugfix.g
